set(FOUNDATION_FEATURES
    FOUNDATION_CONTAINERS
    FOUNDATION_UTILS
    FOUNDATION_TIME
    FOUNDATION_MATH
    FOUNDATION_MATH_RATIO
    FOUNDATION_FUNCTIONAL
    FOUNDATION_FUNCTIONAL_CALLBACK
    FOUNDATION_SCHEDULING
)

foreach(FEATURE IN LISTS FOUNDATION_FEATURES)
    if(NOT DEFINED ${FEATURE})
        set(${FEATURE} ON)
    endif()
endforeach()

include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/FoundationDependencies.cmake")
foundation_validate_dependencies()
