name=Foundation
version=0.1.0
author=Jose Manuel Romo
maintainer=Jose Manuel Romo
sentence=Lightweight C++ foundation library for embedded systems.
paragraph=Reusable containers, time abstractions, scheduling and utility components for MIDILAR, RoboFoundation and standalone embedded projects.
category=Other
url=https://github.com/ChecheRomo96/Foundation
architectures=*
includes=Foundation.h
