var searchData=
[
  ['a_20download_0',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['a_20target_1',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['acceptance_20and_20evidence_2',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['acceptance_20criteria_3',['Acceptance Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'']]],
  ['access_4',['Element Access',['../group__Foundation__Matrix__Fixed.html#FoundationFixedElementAccess',1,'']]],
  ['added_5',['Added',['../md_CHANGELOG.html#autotoc_md9',1,'Added'],['../md_CHANGELOG.html#autotoc_md13',1,'Added'],['../md_CHANGELOG.html#autotoc_md16',1,'Added'],['../md_CHANGELOG.html#autotoc_md19',1,'Added']]],
  ['adding_20a_20target_6',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['adding_20an_20example_7',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['addtask_8',['AddTask',['../classFoundation_1_1Scheduling_1_1BasicTaskScheduler.html#a04b8e94242f4053b4c0d39e07f450263',1,'Foundation::Scheduling::BasicTaskScheduler']]],
  ['aliasing_9',['Aliasing',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicAliasing',1,'']]],
  ['allocate_10',['Allocate',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a4fb2b62e66cb8909554eb736006a7018',1,'Foundation::Math::Matrix::Dynamic']]],
  ['an_20example_11',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['an_20existing_20package_12',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['anatomy_13',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['and_20api_20boundaries_14',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['and_20code_20quality_15',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['and_20cross_20tests_16',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['and_20defaults_17',['and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['and_20evidence_18',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['and_20examples_19',['Tests and Examples',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowTests',1,'']]],
  ['and_20exception_20contract_20',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['and_20export_21',['Build and Export',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Commands',1,'']]],
  ['and_20hardware_20validation_22',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['and_20include_20contract_23',['Build and Include Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'']]],
  ['and_20installation_24',['Build and Installation',['../index.html#MainPage_Build',1,'']]],
  ['and_20license_20status_25',['Release and License Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'']]],
  ['and_20lifetime_26',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['and_20lifetime_20contract_27',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['and_20macos_20checklist_28',['Windows and macOS Checklist',['../group__Foundation__Workflows__DesktopValidation.html',1,'']]],
  ['and_20overrides_29',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['and_20ownership_20review_30',['License and Ownership Review',['../group__Foundation__Workflows__LegalReview.html',1,'']]],
  ['and_20permissions_31',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['and_20publication_32',['Triggers and Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'']]],
  ['and_20sanitizers_33',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['and_20scope_34',['Method and Scope',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'']]],
  ['and_20support_20status_35',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['and_20timing_20contract_36',['Ownership and Timing Contract',['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'']]],
  ['and_20transformations_37',['Type Properties and Transformations',['../group__Foundation__TypeTraits__Properties.html',1,'']]],
  ['and_20validity_38',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['and_20workflow_20hardening_39',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['api_40',['API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['api_20audit_41',['Public API Audit',['../group__Foundation__Workflows__PublicApiAudit.html',1,'']]],
  ['api_20boundaries_42',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['api_20coverage_43',['Public API Coverage',['../group__Foundation__Workflows__PublicApiCoverage.html',1,'']]],
  ['api_20policy_44',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['applications_45',['Applications',['../group__Foundation__Matrix.html#FoundationMatrixApplications',1,'Applications'],['../group__Foundation__Matrix__Fixed.html#FoundationFixedApplications',1,'Applications'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsApplications',1,'Applications']]],
  ['architecture_46',['Module Architecture',['../group__Foundation.html#Foundation_ModuleArchitecture',1,'']]],
  ['arduino_47',['Arduino',['../group__Foundation__BuildGuide__Arduino.html',1,'Arduino'],['../md_README.html#autotoc_md5',1,'Arduino']]],
  ['arduino_20libraries_48',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['arduino_20usage_49',['Arduino Usage',['../group__Foundation.html#FoundationTop_ArduinoUsage',1,'']]],
  ['arguments_20and_20defaults_50',['Arguments and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['arithmetic_20operations_51',['Arithmetic Operations',['../group__Foundation__Matrix__Fixed.html#FoundationFixedArithmetic',1,'']]],
  ['arm_20bare_20metal_20local_20preflight_20—_202026_2009_2025_52',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['arm_20embedded_53',['GNU Arm Embedded',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowArmToolchain',1,'']]],
  ['arm_20profiles_54',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['arm64_20—_202026_2009_2025_55',['macOS Arm64 — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64',1,'']]],
  ['as_20executables_56',['Export as Executables',['../group__Foundation__Examples.html#FoundationExamplesExport',1,'']]],
  ['at_57',['At',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a919865088876a232ae23797896775cc6',1,'Foundation::Math::Matrix::Fixed::At(unsigned int row, unsigned int col)'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a317094579b0b4512fcdc693108fa306c',1,'Foundation::Math::Matrix::Fixed::At(unsigned int row, unsigned int col) const'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a399c48cb0775129afa31b73f971aadd1',1,'Foundation::Math::Matrix::Dynamic::At(unsigned int row, unsigned int col)'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a2a010f1f401d8374fbb4ea311d1ca175',1,'Foundation::Math::Matrix::Dynamic::At(unsigned int row, unsigned int col) const'],['../classFoundation_1_1Time_1_1BasicClock.html#a53300e152387c60c41056780aac0770c',1,'Foundation::Time::BasicClock::At()']]],
  ['atmega328p_20—_202026_2009_2025_58',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['attach_59',['Attach',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a192f3dc67adedf74766066ce88d862e6',1,'Foundation::Math::Matrix::Dynamic']]],
  ['audit_60',['Public API Audit',['../group__Foundation__Workflows__PublicApiAudit.html',1,'']]],
  ['availability_61',['Module Availability',['../group__Foundation.html#FoundationTop_ModuleAvailability',1,'']]],
  ['available_20native_20examples_62',['Available Native Examples',['../group__Foundation__Examples.html#FoundationExamplesAvailable',1,'']]],
  ['avr_63',['AVR',['../group__Foundation__BuildGuide__AVR.html',1,'']]],
  ['avr_20atmega328p_20—_202026_2009_2025_64',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['avr_20gcc_65',['AVR-GCC',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAVRToolchain',1,'']]],
  ['avr_20matrix_66',['AVR Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationAVR',1,'']]]
];
