var searchData=
[
  ['facts_20collected_0',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['failure_20contract_1',['Failure Contract',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicFailure',1,'']]],
  ['failure_20evidence_2',['Failure Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationFailureEvidence',1,'']]],
  ['failures_3',['Common Failures',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildFailures',1,'']]],
  ['families_4',['Supported Families',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFamilies',1,'']]],
  ['feature_20dependencies_5',['Feature Dependencies',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureDependencies',1,'']]],
  ['feature_20matrix_6',['Feature Matrix',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureMatrix',1,'']]],
  ['feature_20set_20matrix_7',['Feature-Set Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'']]],
  ['feature_20variants_8',['Feature Variants',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportFeatures',1,'']]],
  ['features_9',['Features',['../group__Foundation__Matrix__Fixed.html#FoundationFixedFeatures',1,'']]],
  ['files_10',['Files',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFiles',1,'']]],
  ['fill_11',['Fill',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a832a7c2ae5c58f8043d2a991952e0afa',1,'Foundation::Math::Matrix::Fixed::Fill()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a418f5f7c921c51f5dc29bc8050f1f1c6',1,'Foundation::Math::Matrix::Dynamic::Fill()']]],
  ['filled_12',['Filled',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a14992361ac94a700e4967a8b0c348e20',1,'Foundation::Math::Matrix::Fixed']]],
  ['findings_13',['Findings',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditFindings',1,'']]],
  ['firmware_20consumer_20—_202026_2009_2028_14',['STM32G0B1CBT6 firmware consumer — 2026-09-28',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceSTM32G0B1',1,'']]],
  ['firmware_20consumer_20on_20an_20arduino_20uno_20—_202026_2009_2026_15',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['fixed_16',['Fixed',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html',1,'Foundation::Math::Matrix::Fixed&lt; T, Rows, Cols &gt;'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#aa3f081fc380e72d7fedb1802eb1506ce',1,'Foundation::Math::Matrix::Fixed::Fixed()'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#ab67f0764952aabc010d58c5fa5da0b29',1,'Foundation::Math::Matrix::Fixed::Fixed(T value)'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a39d745f26bef78e01e1f60aeb6464a9e',1,'Foundation::Math::Matrix::Fixed::Fixed(const T(&amp;values)[Rows][Cols])'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#acd39e76102669169d5aa2f86fe9fecc5',1,'Foundation::Math::Matrix::Fixed::Fixed(const Fixed&lt; T, Rows, Cols &gt; &amp;other)'],['../md_CHANGELOG.html#autotoc_md11',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md13',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md15',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md17',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md19',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md28',1,'Fixed']]],
  ['fixed_20matrices_17',['Fixed Matrices',['../group__Foundation__Matrix.html#FoundationMatrixFixed',1,'Fixed Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsFixed',1,'Fixed Matrices']]],
  ['fixed_20matrix_18',['Fixed Matrix',['../group__Foundation__Matrix__Fixed.html',1,'']]],
  ['fixed_2eh_19',['Fixed.h',['../Fixed_8h.html',1,'']]],
  ['flip_20',['Flip',['../classFoundation_1_1Containers_1_1BitVector.html#a303c90abc9ab9a97ea4b3d3a89fb1b92',1,'Foundation::Containers::BitVector']]],
  ['flipall_21',['FlipAll',['../classFoundation_1_1Containers_1_1BitVector.html#a6111fa354d81fe5209306329db95dbd6',1,'Foundation::Containers::BitVector']]],
  ['floordiv_22',['FloorDiv',['../group__Foundation__Math.html#gae6916174c5df5224820d61a2cb3761ef',1,'Foundation::Math']]],
  ['floormod_23',['FloorMod',['../group__Foundation__Math.html#ga32978d2f324098fdbe5b3d4f86971c78',1,'Foundation::Math']]],
  ['flow_24',['Flow',['../group__Foundation__Scheduling.html#FoundationSchedulingFlow',1,'Execution Flow'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledRecommendedFlow',1,'Recommended Flow']]],
  ['for_20counsel_25',['Questions for Counsel',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCounsel',1,'']]],
  ['for_20development_26',['Building Examples for Development',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildExamples',1,'']]],
  ['for_20each_20preset_27',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['foundation_28',['Foundation',['../namespaceFoundation.html',1,'Foundation'],['../group__Foundation.html',1,'Foundation'],['../md_README.html',1,'Foundation']]],
  ['foundation_201_20x_20stabilization_20backlog_29',['Foundation 1.x Stabilization Backlog',['../group__Foundation__Workflows__ReleaseV1.html',1,'']]],
  ['foundation_20documentation_30',['Foundation Documentation',['../index.html',1,'']]],
  ['foundation_20h_31',['Foundation.h',['../group__Foundation.html#FoundationTop_FoundationHeader',1,'']]],
  ['foundation_20options_32',['Foundation Options',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureOptions',1,'']]],
  ['foundation_2edox_33',['Foundation.dox',['../Foundation_8dox.html',1,'']]],
  ['foundation_3a_3acontainers_34',['Containers',['../namespaceFoundation_1_1Containers.html',1,'Foundation']]],
  ['foundation_3a_3afunctional_35',['Functional',['../namespaceFoundation_1_1Functional.html',1,'Foundation']]],
  ['foundation_3a_3amath_36',['Math',['../namespaceFoundation_1_1Math.html',1,'Foundation']]],
  ['foundation_3a_3amath_3a_3amatrix_37',['Matrix',['../namespaceFoundation_1_1Math_1_1Matrix.html',1,'Foundation::Math']]],
  ['foundation_3a_3ascheduling_38',['Scheduling',['../namespaceFoundation_1_1Scheduling.html',1,'Foundation']]],
  ['foundation_3a_3atime_39',['Time',['../namespaceFoundation_1_1Time.html',1,'Foundation']]],
  ['foundation_3a_3autils_40',['Utils',['../namespaceFoundation_1_1Utils.html',1,'Foundation']]],
  ['foundation_3a_3autils_3a_3aflash_41',['Flash',['../namespaceFoundation_1_1Utils_1_1Flash.html',1,'Foundation::Utils']]],
  ['foundation_5fbuildsettings_20h_42',['Foundation_BuildSettings.h',['../group__Foundation.html#FoundationTop_FoundationBuildSettingsHeader',1,'']]],
  ['foundation_5fcontainers_20h_43',['Foundation_Containers.h',['../group__Foundation.html#FoundationTop_ContainersHeader',1,'']]],
  ['foundation_5fflash_44',['FOUNDATION_FLASH',['../group__Foundation__Utils.html#gaa4d32913aab8d94af9a7985da6959c20',1,'Flash.h']]],
  ['foundation_5ffunctional_20h_45',['Foundation_Functional.h',['../group__Foundation.html#FoundationTop_FunctionalHeader',1,'']]],
  ['foundation_5fmath_20h_46',['Foundation_Math.h',['../group__Foundation.html#FoundationTop_MathHeader',1,'']]],
  ['foundation_5fscheduling_20h_47',['Foundation_Scheduling.h',['../group__Foundation.html#FoundationTop_SchedulingHeader',1,'']]],
  ['foundation_5ftime_20h_48',['Foundation_Time.h',['../group__Foundation.html#FoundationTop_TimeHeader',1,'']]],
  ['foundation_5futils_20h_49',['Foundation_Utils.h',['../group__Foundation.html#FoundationTop_UtilsHeader',1,'']]],
  ['foundationtop_2edox_50',['FoundationTop.dox',['../FoundationTop_8dox.html',1,'']]],
  ['free_20functions_51',['Free Functions',['../group__Foundation__Callback.html#FoundationCallbackFreeFunctions',1,'']]],
  ['freeze_20decisions_52',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['freeze_20exit_20criteria_53',['Freeze Exit Criteria',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditExit',1,'']]],
  ['frequency_54',['Frequency',['../classFoundation_1_1Time_1_1Frequency.html',1,'Foundation::Time::Frequency'],['../classFoundation_1_1Time_1_1Frequency.html#ad1c661e5e9eed3a1c84f1417956b00f1',1,'Foundation::Time::Frequency::Frequency(uint32_t num=0, uint32_t den=1) noexcept'],['../classFoundation_1_1Time_1_1Frequency.html#a25708e3436264676dbc1b782b8f9fcd6',1,'Foundation::Time::Frequency::Frequency(const Foundation::Math::UnsignedRatio &amp;ratio) noexcept'],['../group__Foundation__Time__Frequency.html',1,'Frequency']]],
  ['fresh_55',['When to Use Fresh',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureFresh',1,'']]],
  ['fresh_20versus_20incremental_56',['Fresh Versus Incremental',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowFresh',1,'']]],
  ['full_20build_57',['Full Build',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledFullBuild',1,'']]],
  ['full_20include_58',['Full Include',['../group__Foundation.html#FoundationTop_FullInclude',1,'']]],
  ['full_20precompiled_20mode_59',['Full Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'']]],
  ['functional_60',['Functional',['../group__Foundation__Functional.html',1,'Functional'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageFunctional',1,'Functional']]],
  ['functional_20module_61',['Functional Module',['../group__Foundation.html#Foundation_FunctionalModule',1,'']]],
  ['functions_62',['Functions',['../group__Foundation__Callback.html#FoundationCallbackFreeFunctions',1,'Free Functions'],['../group__Foundation__Callback.html#FoundationCallbackMemberFunctions',1,'Member Functions']]]
];
