var searchData=
[
  ['a_20download_0',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['a_20target_1',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['acceptance_2',['Acceptance',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureAcceptance',1,'INFRA-001 Acceptance'],['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32G0Hardware',1,'STM32G0B1 Hardware Acceptance']]],
  ['acceptance_20and_20evidence_3',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['acceptance_20criteria_4',['Acceptance Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'']]],
  ['access_5',['Element Access',['../group__Foundation__Matrix__Fixed.html#FoundationFixedElementAccess',1,'']]],
  ['adapter_20contract_6',['Workflow Adapter Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureWorkflowAdapter',1,'']]],
  ['added_7',['Added',['../md_CHANGELOG.html#autotoc_md23',1,'Added'],['../md_CHANGELOG.html#autotoc_md25',1,'Added'],['../md_CHANGELOG.html#autotoc_md29',1,'Added'],['../md_CHANGELOG.html#autotoc_md33',1,'Added'],['../md_CHANGELOG.html#autotoc_md36',1,'Added'],['../md_CHANGELOG.html#autotoc_md39',1,'Added']]],
  ['adding_20a_20target_8',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['adding_20an_20example_9',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['addtask_10',['AddTask',['../classFoundation_1_1Scheduling_1_1BasicTaskScheduler.html#a04b8e94242f4053b4c0d39e07f450263',1,'Foundation::Scheduling::BasicTaskScheduler']]],
  ['aliasing_11',['Aliasing',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicAliasing',1,'']]],
  ['allocate_12',['Allocate',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a4fb2b62e66cb8909554eb736006a7018',1,'Foundation::Math::Matrix::Dynamic']]],
  ['an_20arduino_20uno_20—_202026_2009_2026_13',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['an_20example_14',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['an_20existing_20package_15',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['anatomy_16',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['and_20api_20boundaries_17',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['and_20code_20quality_18',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['and_20cross_20tests_19',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['and_20decision_20',['Status and Decision',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureStatus',1,'']]],
  ['and_20defaults_21',['and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['and_20evidence_22',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['and_20examples_23',['Tests and Examples',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowTests',1,'']]],
  ['and_20exception_20contract_24',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['and_20export_25',['Build and Export',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Commands',1,'']]],
  ['and_20hardware_20validation_26',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['and_20include_20contract_27',['Build and Include Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'']]],
  ['and_20installation_28',['Build and Installation',['../index.html#MainPage_Build',1,'']]],
  ['and_20launcher_20—_202026_2009_2026_29',['macOS Arm64 examples and launcher — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64Examples',1,'']]],
  ['and_20license_20status_30',['Release and License Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'']]],
  ['and_20lifetime_31',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['and_20lifetime_20contract_32',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['and_20macos_20checklist_33',['Windows and macOS Checklist',['../group__Foundation__Workflows__DesktopValidation.html',1,'']]],
  ['and_20non_20goals_34',['Goals and Non-goals',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureGoals',1,'']]],
  ['and_20overrides_35',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['and_20ownership_20review_36',['License and Ownership Review',['../group__Foundation__Workflows__LegalReview.html',1,'']]],
  ['and_20permissions_37',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['and_20pinning_38',['Distribution and Pinning',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureDistribution',1,'']]],
  ['and_20publication_39',['Triggers and Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'']]],
  ['and_20sanitizers_40',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['and_20scope_41',['Method and Scope',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'']]],
  ['and_20support_20status_42',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['and_20timing_20contract_43',['Ownership and Timing Contract',['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'']]],
  ['and_20toolchain_20contract_44',['Preset and Toolchain Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructurePresetContract',1,'']]],
  ['and_20validity_45',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['and_20workflow_20hardening_46',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['api_47',['API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['api_20audit_48',['Public API Audit',['../group__Foundation__Workflows__PublicApiAudit.html',1,'']]],
  ['api_20boundaries_49',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['api_20coverage_50',['Public API Coverage',['../group__Foundation__Workflows__PublicApiCoverage.html',1,'']]],
  ['api_20policy_51',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['applications_52',['Applications',['../group__Foundation__Matrix.html#FoundationMatrixApplications',1,'Applications'],['../group__Foundation__Matrix__Fixed.html#FoundationFixedApplications',1,'Applications'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsApplications',1,'Applications']]],
  ['architecture_53',['Architecture',['../group__Foundation.html#Foundation_ModuleArchitecture',1,'Module Architecture'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureArchitecture',1,'Target Architecture']]],
  ['arduino_54',['Arduino',['../group__Foundation__BuildGuide__Arduino.html',1,'Arduino'],['../md_README.html#autotoc_md7',1,'Arduino']]],
  ['arduino_20libraries_55',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['arduino_20uno_20—_202026_2009_2026_56',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['arduino_20usage_57',['Arduino Usage',['../group__Foundation.html#FoundationTop_ArduinoUsage',1,'']]],
  ['arguments_20and_20defaults_58',['Arguments and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['arithmetic_20operations_59',['Arithmetic Operations',['../group__Foundation__Matrix__Fixed.html#FoundationFixedArithmetic',1,'']]],
  ['arm_20bare_20metal_20local_20preflight_20—_202026_2009_2025_60',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['arm_20embedded_61',['GNU Arm Embedded',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowArmToolchain',1,'']]],
  ['arm_20profiles_62',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['arm64_20—_202026_2009_2025_63',['macOS Arm64 — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64',1,'']]],
  ['arm64_20examples_20and_20launcher_20—_202026_2009_2026_64',['macOS Arm64 examples and launcher — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64Examples',1,'']]],
  ['as_20executables_65',['Export as Executables',['../group__Foundation__Examples.html#FoundationExamplesExport',1,'']]],
  ['assign_66',['Assign',['../classFoundation_1_1Containers_1_1BitVector.html#a7fbbdd0b31fb4dff7a41a8c4008bb7e7',1,'Foundation::Containers::BitVector']]],
  ['at_67',['At',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a919865088876a232ae23797896775cc6',1,'Foundation::Math::Matrix::Fixed::At(unsigned int row, unsigned int col)'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a317094579b0b4512fcdc693108fa306c',1,'Foundation::Math::Matrix::Fixed::At(unsigned int row, unsigned int col) const'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a399c48cb0775129afa31b73f971aadd1',1,'Foundation::Math::Matrix::Dynamic::At(unsigned int row, unsigned int col)'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a2a010f1f401d8374fbb4ea311d1ca175',1,'Foundation::Math::Matrix::Dynamic::At(unsigned int row, unsigned int col) const'],['../classFoundation_1_1Time_1_1BasicClock.html#a53300e152387c60c41056780aac0770c',1,'Foundation::Time::BasicClock::At()']]],
  ['atmega328p_20—_202026_2009_2025_68',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['attach_69',['Attach',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a192f3dc67adedf74766066ce88d862e6',1,'Foundation::Math::Matrix::Dynamic::Attach()'],['../classFoundation_1_1Containers_1_1BitVector.html#a515f77f7d26183041560898da139b29a',1,'Foundation::Containers::BitVector::Attach()']]],
  ['audit_70',['Public API Audit',['../group__Foundation__Workflows__PublicApiAudit.html',1,'']]],
  ['automated_20native_20validation_71',['Automated Native Validation',['../group__Foundation__Examples.html#FoundationExamplesValidation',1,'']]],
  ['availability_72',['Module Availability',['../group__Foundation.html#FoundationTop_ModuleAvailability',1,'']]],
  ['available_20native_20examples_73',['Available Native Examples',['../group__Foundation__Examples.html#FoundationExamplesAvailable',1,'']]],
  ['avr_74',['AVR',['../group__Foundation__BuildGuide__AVR.html',1,'']]],
  ['avr_20atmega328p_20—_202026_2009_2025_75',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['avr_20firmware_20consumer_20on_20an_20arduino_20uno_20—_202026_2009_2026_76',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['avr_20gcc_77',['AVR-GCC',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAVRToolchain',1,'']]],
  ['avr_20matrix_78',['AVR Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationAVR',1,'']]]
];
