var searchData=
[
  ['package_0',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['package_20and_20workflow_20hardening_1',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['package_20boundaries_2',['Package Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPackages',1,'']]],
  ['package_20checks_3',['Package Checks',['../group__Foundation__Workflows__Validation.html#FoundationValidationPackage',1,'']]],
  ['package_20consumer_4',['Installed Package Consumer',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPackageConsumer',1,'']]],
  ['package_20consumer_20validation_5',['Package Consumer Validation',['../group__Foundation__Workflows__PackageConsumer.html',1,'']]],
  ['package_20layout_6',['Package Layout',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportLayout',1,'']]],
  ['package_20matrix_7',['Package Matrix',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesMatrix',1,'']]],
  ['packages_8',['Release Packages',['../group__Foundation__Workflows__ReleasePackages.html',1,'']]],
  ['packet_20checklist_9',['Evidence Packet Checklist',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewPacket',1,'']]],
  ['pages_10',['Related Pages',['../group__Foundation.html#Foundation_RelatedPages',1,'']]],
  ['patterns_11',['Usage Patterns',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsPatterns',1,'']]],
  ['period_12',['Period',['../classFoundation_1_1Time_1_1Period.html',1,'Foundation::Time::Period'],['../classFoundation_1_1Time_1_1Period.html#a670db0fb98ac037c746450b32cda15fd',1,'Foundation::Time::Period::Period(uint32_t num=0, uint32_t den=1) noexcept'],['../classFoundation_1_1Time_1_1Period.html#a578f0fdfc9fc3d42c8c01a012743f2a7',1,'Foundation::Time::Period::Period(const Foundation::Math::UnsignedRatio &amp;ratio) noexcept'],['../group__Foundation__Time__Period.html',1,'Period']]],
  ['periodictask_13',['PeriodicTask',['../namespaceFoundation_1_1Scheduling.html#a7b067f283148c0c21146d8f8eac2e27e',1,'Foundation::Scheduling']]],
  ['periodmicroseconds_14',['PeriodMicroseconds',['../classFoundation_1_1Time_1_1Frequency.html#afb69df35c867f7a273907f75ef5fe604',1,'Foundation::Time::Frequency']]],
  ['periodmilliseconds_15',['PeriodMilliseconds',['../classFoundation_1_1Time_1_1Frequency.html#ae7f04c9e13d17da3e7abaa476ab9023c',1,'Foundation::Time::Frequency']]],
  ['periodseconds_16',['PeriodSeconds',['../classFoundation_1_1Time_1_1Frequency.html#a79bf381845cf6178dd32445858850419',1,'Foundation::Time::Frequency']]],
  ['permissions_17',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['pi_18',['Pi',['../group__Foundation__Math.html#ga6041f80745281de174961a2cac7fd43b',1,'Foundation::Math']]],
  ['platform_20and_20hardware_20validation_19',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['platform_20scope_20',['Platform Scope',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPlatforms',1,'']]],
  ['platforms_21',['Platforms',['../group__Foundation__BuildGuide__Platforms.html',1,'Platforms'],['../group__Foundation.html#Foundation_TargetPlatforms',1,'Target Platforms']]],
  ['platforms_20and_20support_20status_22',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['point_23',['Time Point',['../group__Foundation__Time__TimePoint.html',1,'']]],
  ['policy_24',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['pop_25',['Pop',['../classFoundation_1_1Containers_1_1CircularBuffer.html#aecb5dfcde064edb31866a2fa0c5ddc97',1,'Foundation::Containers::CircularBuffer::Pop()'],['../classFoundation_1_1Containers_1_1Stack.html#aa7202ed6bbe0636a9c3b60e41d43b722',1,'Foundation::Containers::Stack::Pop()']]],
  ['position_26',['Current Position',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCurrent',1,'']]],
  ['powershell_27',['PowerShell',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigurePowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Install.html#FoundationWorkflowInstallPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Clean.html#FoundationWorkflowCleanPowerShell',1,'PowerShell']]],
  ['precompiled_20arduino_20libraries_28',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['precompiled_20libraries_29',['Precompiled Libraries',['../group__Foundation__Workflows__Precompiled.html',1,'']]],
  ['precompiled_20mode_30',['Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'Custom Precompiled Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'Full Precompiled Mode']]],
  ['preflight_31',['Common Preflight',['../group__Foundation__Workflows__Validation.html#FoundationValidationPreflight',1,'']]],
  ['preflight_20—_202026_2009_2025_32',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['prerequisites_33',['Prerequisites',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPrerequisites',1,'']]],
  ['presentation_20contract_34',['Presentation Contract',['../group__Foundation__Examples.html#FoundationExamplesPresentation',1,'']]],
  ['preset_35',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['preset_20anatomy_36',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['presets_37',['Presets',['../group__Foundation__Workflows__Presets.html',1,'Presets'],['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixWorkflowPresets',1,'Workflow-Only Presets']]],
  ['primary_20type_20categories_38',['Primary Type Categories',['../group__Foundation__TypeTraits__Primary.html',1,'']]],
  ['prioritized_20test_20work_39',['Prioritized Test Work',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageNext',1,'']]],
  ['procedure_40',['Release Procedure',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesReleaseProcedure',1,'']]],
  ['profiles_41',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['properties_20and_20transformations_42',['Type Properties and Transformations',['../group__Foundation__TypeTraits__Properties.html',1,'']]],
  ['proves_43',['What It Proves',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCoverage',1,'']]],
  ['psoc_44',['PSoC',['../group__Foundation__BuildGuide__PSoC.html',1,'']]],
  ['psoc_20creator_20usage_45',['PSoC Creator Usage',['../group__Foundation.html#FoundationTop_PSoCUsage',1,'']]],
  ['public_20api_46',['Public API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['public_20api_20audit_47',['Public API Audit',['../group__Foundation__Workflows__PublicApiAudit.html',1,'']]],
  ['public_20api_20coverage_48',['Public API Coverage',['../group__Foundation__Workflows__PublicApiCoverage.html',1,'']]],
  ['public_20api_20policy_49',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['public_20headers_50',['Public Headers',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsHeaders',1,'Public Headers'],['../group__Foundation__Containers.html#FoundationContainersHeaders',1,'Public Headers'],['../group__Foundation__Functional.html#FoundationFunctionalHeaders',1,'Public Headers'],['../group__Foundation__Time.html#FoundationTimeHeaders',1,'Public Headers'],['../group__Foundation__Scheduling.html#FoundationSchedulingHeaders',1,'Public Headers'],['../group__Foundation__Utils.html#FoundationUtilsHeaders',1,'Public Headers']]],
  ['public_20surface_20inventory_51',['Public Surface Inventory',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditInventory',1,'']]],
  ['public_20types_52',['Public Types',['../group__Foundation__Time.html#FoundationTimeTypes',1,'Public Types'],['../group__Foundation__Scheduling.html#FoundationSchedulingTypes',1,'Public Types']]],
  ['publication_53',['Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'Triggers and Publication'],['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowVerify',1,'Verification Before Publication']]],
  ['publication_54',['[1.0.0] - Superseded before publication',['../md_CHANGELOG.html#autotoc_md18',1,'']]],
  ['push_55',['Push',['../classFoundation_1_1Containers_1_1CircularBuffer.html#adca3213772f5c22b5df3057b118908a8',1,'Foundation::Containers::CircularBuffer::Push(const T &amp;value)'],['../classFoundation_1_1Containers_1_1CircularBuffer.html#a0f4e0c23b679645db1d99b04f09b3bf4',1,'Foundation::Containers::CircularBuffer::Push(T &amp;&amp;value)'],['../classFoundation_1_1Containers_1_1Stack.html#accbeeeb323a61281375c9552c6d454bc',1,'Foundation::Containers::Stack::Push(const T &amp;value)'],['../classFoundation_1_1Containers_1_1Stack.html#a43fe10ad1df555dd826feb79515d7cf8',1,'Foundation::Containers::Stack::Push(T &amp;&amp;value)']]]
];
