var searchData=
[
  ['target_0',['Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'Adding a Target'],['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRTarget',1,'Initial Supported Target'],['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCTarget',1,'Initial Supported Target']]],
  ['target_20only_20evidence_1',['Target-only Evidence',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageTarget',1,'']]],
  ['target_20platforms_2',['Target Platforms',['../group__Foundation.html#Foundation_TargetPlatforms',1,'']]],
  ['target_20platforms_20and_20support_20status_3',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['targets_4',['Targets',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixEmbedded',1,'Named Embedded Targets'],['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixDesktop',1,'Native Desktop Targets']]],
  ['task_5',['Task',['../namespaceFoundation_1_1Scheduling.html#a747a9498d7a338b140b76981a1ff4a0c',1,'Foundation::Scheduling']]],
  ['taskscheduler_6',['TaskScheduler',['../namespaceFoundation_1_1Scheduling.html#a03d3b4a77f71f8c460f5259c52a313dd',1,'Foundation::Scheduling']]],
  ['test_7',['Test',['../group__Foundation__Workflows__Test.html',1,'']]],
  ['test_20depth_20and_20code_20quality_8',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['test_20status_9',['Test Status',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsTests',1,'']]],
  ['test_20suite_20scope_10',['Test-Suite Scope',['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'']]],
  ['test_20work_11',['Prioritized Test Work',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageNext',1,'']]],
  ['tests_12',['Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'Native and Cross Tests'],['../md_README.html#autotoc_md3',1,'Tests']]],
  ['tests_20and_20examples_13',['Tests and Examples',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowTests',1,'']]],
  ['the_20result_14',['Inspecting the Result',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureInspect',1,'']]],
  ['through_20cmake_15',['Build Through CMake',['../group__Foundation__Examples.html#FoundationExamplesBuild',1,'']]],
  ['tick_16',['Tick',['../classFoundation_1_1Time_1_1Tick.html',1,'Foundation::Time::Tick&lt; T &gt;'],['../classFoundation_1_1Time_1_1Tick.html#ac66d15b473b59d91bfc29f88d2fb01e2',1,'Foundation::Time::Tick::Tick()'],['../group__Foundation__Time__Tick.html',1,'Tick']]],
  ['tick_20representations_17',['Tick Representations',['../group__Foundation__Time.html#FoundationTimeRepresentations',1,'']]],
  ['tick_20type_20consistency_18',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['tick16_19',['Tick16',['../namespaceFoundation_1_1Time.html#a9e3b0de97783f178e8cc8d56be3408a2',1,'Foundation::Time']]],
  ['tick32_20',['Tick32',['../namespaceFoundation_1_1Time.html#aa4107748c8655eae65e3b5ab5ae20ca7',1,'Foundation::Time']]],
  ['tick64_21',['Tick64',['../namespaceFoundation_1_1Time.html#a61f6240f6da65dcd4d9cbe5a0f477eca',1,'Foundation::Time']]],
  ['tick8_22',['Tick8',['../namespaceFoundation_1_1Time.html#a61a257e1de8912831e1d2760edd906b9',1,'Foundation::Time']]],
  ['tick_3c_20uint16_5ft_20_3e_23',['Tick&lt; uint16_t &gt;',['../classFoundation_1_1Time_1_1Tick.html',1,'Foundation::Time']]],
  ['tick_3c_20uint32_5ft_20_3e_24',['Tick&lt; uint32_t &gt;',['../classFoundation_1_1Time_1_1Tick.html',1,'Foundation::Time']]],
  ['tick_3c_20uint64_5ft_20_3e_25',['Tick&lt; uint64_t &gt;',['../classFoundation_1_1Time_1_1Tick.html',1,'Foundation::Time']]],
  ['tick_3c_20uint8_5ft_20_3e_26',['Tick&lt; uint8_t &gt;',['../classFoundation_1_1Time_1_1Tick.html',1,'Foundation::Time']]],
  ['ticks_27',['Ticks',['../classFoundation_1_1Time_1_1BasicDuration.html#aecb1cfc0cbe7df520d1003120fb15c08',1,'Foundation::Time::BasicDuration::Ticks()'],['../classFoundation_1_1Time_1_1BasicTimePoint.html#afb906ea22c5a17af919406eb66030a4a',1,'Foundation::Time::BasicTimePoint::Ticks()']]],
  ['time_28',['Time',['../group__Foundation__Time.html',1,'Time'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageTime',1,'Time']]],
  ['time_20and_20exception_20contract_29',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['time_20and_20validity_30',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['time_20module_31',['Time Module',['../group__Foundation.html#Foundation_TimeModule',1,'']]],
  ['time_20point_32',['Time Point',['../group__Foundation__Time__TimePoint.html',1,'']]],
  ['timepoint_33',['TimePoint',['../namespaceFoundation_1_1Time.html#a9819eb4df4ec30cda19c879aa4a10514',1,'Foundation::Time']]],
  ['timing_20contract_34',['Ownership and Timing Contract',['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'']]],
  ['to_20use_20fresh_35',['When to Use Fresh',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureFresh',1,'']]],
  ['tofloat_36',['ToFloat',['../classFoundation_1_1Math_1_1BasicRatio.html#a1bb2e56960b0186eb07c2a7b37741195',1,'Foundation::Math::BasicRatio']]],
  ['toolchain_20configuration_37',['Toolchain Configuration',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRToolchain',1,'']]],
  ['toolchains_38',['Toolchains',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsToolchains',1,'Supported Windows Toolchains'],['../group__Foundation__Workflows__Toolchains.html',1,'Toolchains']]],
  ['top_20level_20header_20list_39',['Top-Level Header List',['../group__Foundation.html#FoundationTop_HeaderList',1,'']]],
  ['top_20level_20headers_40',['Top-Level Headers',['../group__Foundation.html',1,'']]],
  ['topics_41',['Related Topics',['../group__Foundation.html#FoundationTop_RelatedTopics',1,'']]],
  ['trait_20families_42',['Trait Families',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsFamilies',1,'']]],
  ['traits_43',['Type Traits',['../group__Foundation__TypeTraits.html',1,'']]],
  ['traits_20module_44',['Type Traits Module',['../group__Foundation.html#Foundation_TypeTraitsModule',1,'']]],
  ['transformations_45',['Type Properties and Transformations',['../group__Foundation__TypeTraits__Properties.html',1,'']]],
  ['transpose_46',['Transpose',['../group__Foundation__Matrix__Fixed.html#FoundationFixedTranspose',1,'']]],
  ['transposed_47',['Transposed',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#ad3f327e9667cac22488acec24adf808e',1,'Foundation::Math::Matrix::Fixed::Transposed()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a78edc9855186f50609fda8f2f3300ceb',1,'Foundation::Math::Matrix::Dynamic::Transposed() const']]],
  ['transposeto_48',['TransposeTo',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a74acd0cd86a2dec68261746767b967fa',1,'Foundation::Math::Matrix::Dynamic']]],
  ['triggers_20and_20permissions_49',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['triggers_20and_20publication_50',['Triggers and Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'']]],
  ['trigonometry_2eh_51',['Trigonometry.h',['../Trigonometry_8h.html',1,'']]],
  ['true_5ftype_52',['true_type',['../group__Foundation__TypeTraits__Helpers.html#ga0bd5fb87c4bc53d708b5c9a2f79a97ea',1,'Foundation::TypeTraits']]],
  ['type_20categories_53',['Type Categories',['../group__Foundation__TypeTraits__Composite.html',1,'Composite Type Categories'],['../group__Foundation__TypeTraits__Primary.html',1,'Primary Type Categories']]],
  ['type_20consistency_54',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['type_20properties_20and_20transformations_55',['Type Properties and Transformations',['../group__Foundation__TypeTraits__Properties.html',1,'']]],
  ['type_20relationships_56',['Type Relationships',['../group__Foundation__TypeTraits__Relationships.html',1,'']]],
  ['type_20traits_57',['Type Traits',['../group__Foundation__TypeTraits.html',1,'']]],
  ['type_20traits_20module_58',['Type Traits Module',['../group__Foundation.html#Foundation_TypeTraitsModule',1,'']]],
  ['types_59',['Types',['../group__Foundation__Containers.html#FoundationContainersTypes',1,'Container Types'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageLegend',1,'Evidence Types'],['../group__Foundation__Matrix.html#FoundationMatrixTypes',1,'Matrix Types'],['../group__Foundation__Time.html#FoundationTimeTypes',1,'Public Types'],['../group__Foundation__Scheduling.html#FoundationSchedulingTypes',1,'Public Types']]],
  ['typetraits_60',['TypeTraits',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageTypeTraits',1,'']]],
  ['typetraits_20basicchecks_61',['TypeTraits BasicChecks',['../group__Foundation__Examples.html#FoundationExamplesTypeTraits',1,'']]],
  ['typetraits_20evidence_62',['TypeTraits Evidence',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditTraitEvidence',1,'']]]
];
