var searchData=
[
  ['daily_20development_0',['Daily Development',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDaily',1,'']]],
  ['data_1',['Data',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a743eb47d802f58aacee50094b0afc8f1',1,'Foundation::Math::Matrix::Fixed::Data()'],['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a70865835dcd2f4ffd6778438850d1021',1,'Foundation::Math::Matrix::Fixed::Data() const'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#af1ec2e4c93ecd15624b33aa5c62fa4da',1,'Foundation::Math::Matrix::Dynamic::Data()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a3dd862bd7654b95b7994fda5b62fc799',1,'Foundation::Math::Matrix::Dynamic::Data() const']]],
  ['decisions_2',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['defaults_3',['Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['degtorad_4',['DegToRad',['../group__Foundation__Math.html#ga13cb3843e5e8cf4af18166f2dc06b6df',1,'Foundation::Math']]],
  ['delivery_5',['Delivery',['../group__Foundation__Workflows__Delivery.html',1,'']]],
  ['denominator_6',['Denominator',['../classFoundation_1_1Math_1_1BasicRatio.html#abf23cbb9f9c7fe82d5186d649ebdb0fe',1,'Foundation::Math::BasicRatio::Denominator()'],['../classFoundation_1_1Time_1_1Frequency.html#a29ba27f7af5779bac97af7415e0a5490',1,'Foundation::Time::Frequency::Denominator()'],['../classFoundation_1_1Time_1_1Period.html#a625df75d9f127d71cdc68c7f4f60cabd',1,'Foundation::Time::Period::Denominator()']]],
  ['dependencies_7',['Dependencies',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureDependencies',1,'Feature Dependencies'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditDependencies',1,'Module Dependencies']]],
  ['dependency_8',['GoogleTest Dependency',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestDependency',1,'']]],
  ['dependency_20model_9',['Dependency Model',['../group__Foundation.html#Foundation_DependencyModel',1,'']]],
  ['dependency_20roadmap_10',['Dependency Roadmap',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Roadmap',1,'']]],
  ['depth_20and_20code_20quality_11',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['design_20goals_12',['Design Goals',['../group__Foundation.html#Foundation_DesignGoals',1,'Design Goals'],['../index.html#MainPage_DesignGoals',1,'Design Goals']]],
  ['desktop_13',['Desktop',['../group__Foundation__BuildGuide__DesktopPlatforms.html',1,'']]],
  ['desktop_20matrix_14',['Desktop Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationDesktop',1,'']]],
  ['desktop_20targets_15',['Native Desktop Targets',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixDesktop',1,'']]],
  ['desktop_20usage_16',['Desktop Usage',['../group__Foundation.html#FoundationTop_DesktopUsage',1,'']]],
  ['development_17',['Development',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildExamples',1,'Building Examples for Development'],['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDaily',1,'Daily Development'],['../group__Foundation__Workflows__Development.html',1,'Development']]],
  ['directories_18',['Workflow Directories',['../group__Foundation__Workflows.html#FoundationWorkflowsDirectories',1,'']]],
  ['documentation_19',['Documentation',['../group__Foundation__Workflows__Documentation.html',1,'Documentation'],['../index.html',1,'Foundation Documentation']]],
  ['documentation_20changes_20',['Documentation Changes',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDocs',1,'']]],
  ['documentation_20layout_21',['Documentation Layout',['../group__Foundation.html#Foundation_DocumentationLayout',1,'']]],
  ['documentation_20validation_22',['Documentation Validation',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationDocumentation',1,'']]],
  ['download_23',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['duration_24',['Duration',['../namespaceFoundation_1_1Time.html#a6ee3d50b98da2e9ef1dc18dcf83c12fb',1,'Foundation::Time::Duration'],['../group__Foundation__Time__Duration.html',1,'Duration']]],
  ['dynamic_25',['Dynamic',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html',1,'Foundation::Math::Matrix::Dynamic&lt; T &gt;'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a6b566b605bd68db455b5fbed4aef0bf3',1,'Foundation::Math::Matrix::Dynamic::Dynamic()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#ab645316a5d8354c8e9b848289a7d04cd',1,'Foundation::Math::Matrix::Dynamic::Dynamic(unsigned int rows, unsigned int cols)'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a23417df0aa1e27ed451a07b5b4423cba',1,'Foundation::Math::Matrix::Dynamic::Dynamic(unsigned int rows, unsigned int cols, T value)'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a55a7ad17580441b2d04216d9b1f21c8d',1,'Foundation::Math::Matrix::Dynamic::Dynamic(unsigned int rows, unsigned int cols, T *externalData)'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a955c92b1c54ac542a64eb126b81e6647',1,'Foundation::Math::Matrix::Dynamic::Dynamic(const Dynamic&lt; T &gt; &amp;other)'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a54400627d0b3014de82110184c4b0068',1,'Foundation::Math::Matrix::Dynamic::Dynamic(Dynamic&lt; T &gt; &amp;&amp;other) noexcept']]],
  ['dynamic_20matrices_26',['Dynamic Matrices',['../group__Foundation__Matrix.html#FoundationMatrixDynamic',1,'Dynamic Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsDynamic',1,'Dynamic Matrices']]],
  ['dynamic_20matrix_27',['Dynamic Matrix',['../group__Foundation__Matrix__Dynamic.html',1,'']]],
  ['dynamic_20memory_28',['Dynamic Memory',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRMemory',1,'']]]
];
