var searchData=
[
  ['sameclock_0',['SameClock',['../classFoundation_1_1Time_1_1BasicTimePoint.html#a6dcc853dc6c236c14e6973462ab93340',1,'Foundation::Time::BasicTimePoint']]],
  ['sanitizers_1',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['scheduling_2',['Scheduling',['../group__Foundation__Scheduling.html',1,'Scheduling'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageScheduling',1,'Scheduling']]],
  ['scheduling_20module_3',['Scheduling Module',['../group__Foundation.html#Foundation_SchedulingModule',1,'']]],
  ['scope_4',['Scope',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Scope',1,'Library Scope'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'Method and Scope'],['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPlatforms',1,'Platform Scope'],['../group__Foundation__Workflows__Clean.html#FoundationWorkflowCleanScope',1,'Scope'],['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'Test-Suite Scope']]],
  ['seconds_5',['Seconds',['../classFoundation_1_1Time_1_1Period.html#acf2280f8b5675f56115b916940163b5d',1,'Foundation::Time::Period::Seconds()'],['../classFoundation_1_1Time_1_1BasicDuration.html#ad15ce9e4c9d72e6a2c36c1851ffca5a6',1,'Foundation::Time::BasicDuration::Seconds()']]],
  ['sections_6',['Sections',['../group__Foundation__BuildGuide.html#FoundationBuildGuideSections',1,'']]],
  ['selective_20include_7',['Selective Include',['../group__Foundation.html#FoundationTop_SelectiveInclude',1,'']]],
  ['sequence_8',['Sequence',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRCommands',1,'Complete Local Sequence'],['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationSequence',1,'Job Sequence'],['../group__Foundation__Workflows.html#FoundationWorkflowsSequence',1,'Normal Release Sequence']]],
  ['set_9',['Set',['../classFoundation_1_1Math_1_1BasicRatio.html#ac1f3dbfde3706050aec60ff84b44f332',1,'Foundation::Math::BasicRatio::Set()'],['../classFoundation_1_1Time_1_1Frequency.html#afc9bf24240d9a571e3e77b21b4b40fe4',1,'Foundation::Time::Frequency::Set()'],['../classFoundation_1_1Time_1_1Period.html#a6e26f45d6ae63e90f071912ab6e00904',1,'Foundation::Time::Period::Set()']]],
  ['set_20matrix_10',['Feature-Set Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'']]],
  ['setdenominator_11',['SetDenominator',['../classFoundation_1_1Math_1_1BasicRatio.html#a8c5f5eaebd2114c8ed350081a1ecd3bd',1,'Foundation::Math::BasicRatio::SetDenominator()'],['../classFoundation_1_1Time_1_1Frequency.html#aaeb69d13ad9e5eda793bb2c4541bf62b',1,'Foundation::Time::Frequency::SetDenominator()'],['../classFoundation_1_1Time_1_1Period.html#ad86093f80b9091a564d3619a151a58f8',1,'Foundation::Time::Period::SetDenominator()']]],
  ['setfrequency_12',['SetFrequency',['../classFoundation_1_1Time_1_1BasicClock.html#aba07cbd41daa7186cccd9d50950654ff',1,'Foundation::Time::BasicClock']]],
  ['setnumerator_13',['SetNumerator',['../classFoundation_1_1Math_1_1BasicRatio.html#ae268c756ca4625de94e55335e8613b8d',1,'Foundation::Math::BasicRatio::SetNumerator()'],['../classFoundation_1_1Time_1_1Frequency.html#a8ec0729ccaa1230a7c0107fe46b2bd64',1,'Foundation::Time::Frequency::SetNumerator()'],['../classFoundation_1_1Time_1_1Period.html#a5b9bbb0092dc4996e13e9a6210a55ee1',1,'Foundation::Time::Period::SetNumerator()']]],
  ['setticks_14',['SetTicks',['../classFoundation_1_1Time_1_1BasicDuration.html#adbce93677a00e7ade75c59f18351fe93',1,'Foundation::Time::BasicDuration']]],
  ['settings_20header_15',['Build Settings Header',['../group__Foundation.html#FoundationTop_BuildSettingsHeader',1,'']]],
  ['setvalue_16',['SetValue',['../classFoundation_1_1Time_1_1Tick.html#a35a625ea774f1545c520c96a385bfe70',1,'Foundation::Time::Tick']]],
  ['severity_17',['Severity',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditSeverity',1,'']]],
  ['shouldrun_18',['ShouldRun',['../classFoundation_1_1Scheduling_1_1BasicTask.html#aaf8a1d7b7d64992e934ef42611535285',1,'Foundation::Scheduling::BasicTask::ShouldRun()'],['../classFoundation_1_1Scheduling_1_1BasicPeriodicTask.html#aa74bed3fb28bdbf137f269fd9b820102',1,'Foundation::Scheduling::BasicPeriodicTask::ShouldRun()'],['../classFoundation_1_1Scheduling_1_1BasicOneShotTask.html#aae0452dae177eb5a932dff2428cd7aa0',1,'Foundation::Scheduling::BasicOneShotTask::ShouldRun()']]],
  ['sign_19',['Sign',['../classFoundation_1_1Math_1_1BasicRatio.html#a1f990bb912dcc68be3fb3dcc2e86a06d',1,'Foundation::Math::BasicRatio']]],
  ['signature_20model_20',['Signature Model',['../group__Foundation__Callback.html#FoundationCallbackSignatures',1,'']]],
  ['size_21',['Size',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a8d34e25b5df654e392e3214bbe81a0e2',1,'Foundation::Math::Matrix::Dynamic']]],
  ['source_20mode_22',['Source Mode',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoSource',1,'Source Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildSourceMode',1,'Source Mode']]],
  ['source_20mode_20integrations_23',['Source-Mode Integrations',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixSourceMode',1,'']]],
  ['stabilization_20backlog_24',['Foundation 1.x Stabilization Backlog',['../group__Foundation__Workflows__ReleaseV1.html',1,'']]],
  ['stack_25',['Stack',['../classFoundation_1_1Containers_1_1Stack.html',1,'Foundation::Containers::Stack&lt; T &gt;'],['../classFoundation_1_1Containers_1_1Stack.html#a89270fba9ea070ff36e56687709c1cc1',1,'Foundation::Containers::Stack::Stack()']]],
  ['started_26',['Getting Started',['../index.html#MainPage_GettingStarted',1,'']]],
  ['state_27',['Cached State',['../group__Foundation__Workflows.html#FoundationWorkflowsState',1,'']]],
  ['state_20and_20lifetime_28',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['status_29',['Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'Release and License Status'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditStatus',1,'Status'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageStatus',1,'Status'],['../index.html#MainPage_Platforms',1,'Target Platforms and Support Status'],['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsTests',1,'Test Status']]],
  ['status_20header_30',['Status Header',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Status',1,'']]],
  ['steps_31',['Next Steps',['../index.html#MainPage_NextSteps',1,'']]],
  ['still_20open_32',['Quality Gates Still Open',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsQuality',1,'']]],
  ['stm32_33',['STM32',['../group__Foundation__BuildGuide__STM32.html',1,'']]],
  ['stm32_20matrix_34',['STM32 Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationSTM32',1,'']]],
  ['stm32_20rule_35',['STM32 Rule',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Rule',1,'']]],
  ['storage_36',['External Storage',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicExternalStorage',1,'']]],
  ['storage_20and_20lifetime_20contract_37',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['strategies_38',['Include Strategies',['../group__Foundation.html#FoundationTop_IncludeStrategies',1,'']]],
  ['structure_39',['Group Structure',['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsStructure',1,'']]],
  ['style_40',['Coding Style',['../group__Foundation.html#Foundation_Style',1,'']]],
  ['suite_41',['Registered Native Suite',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestSuite',1,'']]],
  ['suite_20scope_42',['Test-Suite Scope',['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'']]],
  ['superseded_20before_20publication_43',['[1.0.0] - Superseded before publication',['../md_CHANGELOG.html#autotoc_md18',1,'']]],
  ['support_20levels_44',['Support Levels',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixLevels',1,'']]],
  ['support_20matrix_45',['Support Matrix',['../group__Foundation__BuildGuide__SupportMatrix.html',1,'']]],
  ['support_20status_46',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['supported_20families_47',['Supported Families',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFamilies',1,'']]],
  ['supported_20target_48',['Supported Target',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRTarget',1,'Initial Supported Target'],['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCTarget',1,'Initial Supported Target']]],
  ['supported_20v1_20surface_49',['Supported v1 Surface',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsSurface',1,'']]],
  ['supported_20windows_20toolchains_50',['Supported Windows Toolchains',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsToolchains',1,'']]],
  ['surface_51',['Supported v1 Surface',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsSurface',1,'']]],
  ['surface_20inventory_52',['Public Surface Inventory',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditInventory',1,'']]],
  ['sustained_201_20x_20releases_53',['M6 - Sustained 1.x Releases',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M6',1,'']]],
  ['swap_54',['Swap',['../group__Foundation__Utils.html#gae8d4ee98298fad008fbbf4bd76c5064a',1,'Foundation::Utils']]],
  ['system_55',['Build System',['../group__Foundation.html#Foundation_BuildSystem',1,'']]]
];
