var searchData=
[
  ['radtodeg_0',['RadToDeg',['../group__Foundation__Math.html#ga38d8a7c55cfc2028f3b5beb2aee0e98e',1,'Foundation::Math']]],
  ['ratio_1',['Ratio',['../namespaceFoundation_1_1Math.html#a21e984629de75450106f334c50b0fdc2',1,'Foundation::Math::Ratio'],['../group__Foundation__Math__Ratio.html',1,'Ratio']]],
  ['read_2',['Read',['../group__Foundation__Utils.html#gaf51f5f60433b4301589ea10d1f9c18a5',1,'Foundation::Utils::Flash']]],
  ['real_3',['real',['../classFoundation_1_1Math_1_1Complex.html#add5e156b4f531b25fff3919df57e6d5e',1,'Foundation::Math::Complex']]],
  ['recommended_20flow_4',['Recommended Flow',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledRecommendedFlow',1,'']]],
  ['recommended_20freeze_20decisions_5',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['recommended_20usage_6',['Recommended Usage',['../group__Foundation.html#FoundationTop_RecommendedUsage',1,'']]],
  ['record_7',['Result Record',['../group__Foundation__Workflows__Validation.html#FoundationValidationReport',1,'']]],
  ['recorded_20evidence_8',['Recorded Evidence',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidence',1,'']]],
  ['reduce_9',['Reduce',['../classFoundation_1_1Math_1_1BasicRatio.html#a2028849516a2b98663e8199b97040662',1,'Foundation::Math::BasicRatio']]],
  ['reduced_10',['Reduced',['../classFoundation_1_1Math_1_1BasicRatio.html#aaf382f8fa498a5c0f10501d4fdf103ec',1,'Foundation::Math::BasicRatio']]],
  ['registered_20native_20suite_11',['Registered Native Suite',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestSuite',1,'']]],
  ['related_20components_12',['Related Components',['../group__Foundation__Callback.html#FoundationCallbackRelated',1,'']]],
  ['related_20modules_13',['Related Modules',['../group__Foundation__Matrix.html#FoundationMatrixRelated',1,'']]],
  ['related_20pages_14',['Related Pages',['../group__Foundation.html#Foundation_RelatedPages',1,'']]],
  ['related_20topics_15',['Related Topics',['../group__Foundation.html#FoundationTop_RelatedTopics',1,'']]],
  ['relationships_16',['Type Relationships',['../group__Foundation__TypeTraits__Relationships.html',1,'']]],
  ['release_20and_20license_20status_17',['Release and License Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'']]],
  ['release_20candidate_20export_18',['Release-Candidate Export',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowExport',1,'']]],
  ['release_20contract_19',['M1 - Release Contract',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M1',1,'']]],
  ['release_20evidence_20',['Release Evidence',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationExit',1,'']]],
  ['release_20gates_21',['Release Gates',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Gates',1,'']]],
  ['release_20packages_22',['Release Packages',['../group__Foundation__Workflows__ReleasePackages.html',1,'']]],
  ['release_20procedure_23',['Release Procedure',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesReleaseProcedure',1,'']]],
  ['release_20rule_24',['Release Rule',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixReleaseRule',1,'']]],
  ['release_20sequence_25',['Normal Release Sequence',['../group__Foundation__Workflows.html#FoundationWorkflowsSequence',1,'']]],
  ['releases_26',['M6 - Sustained 1.x Releases',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M6',1,'']]],
  ['remove_5fconst_27',['remove_const',['../structFoundation_1_1TypeTraits_1_1remove__const.html',1,'Foundation::TypeTraits']]],
  ['remove_5fconst_5ft_28',['remove_const_t',['../group__Foundation__TypeTraits__Properties.html#ga1edf6b71ec00859193de756b3065218c',1,'Foundation::TypeTraits']]],
  ['remove_5fcv_29',['remove_cv',['../structFoundation_1_1TypeTraits_1_1remove__cv.html',1,'Foundation::TypeTraits']]],
  ['remove_5fcv_5ft_30',['remove_cv_t',['../group__Foundation__TypeTraits__Properties.html#gae425faf745bda83578e3d3bc6573b2ee',1,'Foundation::TypeTraits']]],
  ['remove_5fvolatile_31',['remove_volatile',['../structFoundation_1_1TypeTraits_1_1remove__volatile.html',1,'Foundation::TypeTraits']]],
  ['remove_5fvolatile_5ft_32',['remove_volatile_t',['../group__Foundation__TypeTraits__Properties.html#ga4a835ac9381108f424b593809ebc79f6',1,'Foundation::TypeTraits']]],
  ['repository_20facts_20collected_33',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['repository_20layout_34',['Repository Layout',['../index.html#MainPage_RepositoryLayout',1,'']]],
  ['representation_35',['Representation',['../classFoundation_1_1Math_1_1BasicRatio.html#a096f1e8b6b4b8017de8c12a1097a1f75',1,'Foundation::Math::BasicRatio']]],
  ['representations_36',['Tick Representations',['../group__Foundation__Time.html#FoundationTimeRepresentations',1,'']]],
  ['required_20matrix_37',['Required Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMatrix',1,'']]],
  ['requirements_38',['Requirements',['../index.html#MainPage_Requirements',1,'']]],
  ['reset_39',['Reset',['../classFoundation_1_1Containers_1_1CircularBuffer.html#a1c8b4e6883334b31c5e83b8c4585bdf0',1,'Foundation::Containers::CircularBuffer::Reset()'],['../classFoundation_1_1Containers_1_1Stack.html#a773a0a2bc7c51c07604882838b285acd',1,'Foundation::Containers::Stack::Reset()']]],
  ['responsibilities_40',['Responsibilities',['../group__Foundation__Workflows.html#FoundationWorkflowsResponsibilities',1,'']]],
  ['responsibility_41',['Header Responsibility',['../group__Foundation.html#FoundationTop_HeaderResponsibility',1,'']]],
  ['result_42',['Inspecting the Result',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureInspect',1,'']]],
  ['result_20record_43',['Result Record',['../group__Foundation__Workflows__Validation.html#FoundationValidationReport',1,'']]],
  ['return_20values_44',['Return Values',['../group__Foundation__Callback.html#FoundationCallbackReturnValues',1,'']]],
  ['reusable_20ci_20contract_45',['Reusable CI Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureCI',1,'']]],
  ['reusing_20an_20existing_20package_46',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['review_47',['License and Ownership Review',['../group__Foundation__Workflows__LegalReview.html',1,'']]],
  ['roadmap_48',['Dependency Roadmap',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Roadmap',1,'']]],
  ['rosetta_202_20—_202026_2009_2026_49',['macOS x86-64 through Rosetta 2 — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSx64',1,'']]],
  ['rowcount_50',['RowCount',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a7288af391bf2a9d52b90c81d720613a9',1,'Foundation::Math::Matrix::Fixed::RowCount()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a13e9383ca35646362888d43ceb0282b6',1,'Foundation::Math::Matrix::Dynamic::RowCount()']]],
  ['rule_51',['Rule',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportCompatibility',1,'Compatibility Rule'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildRule',1,'General Rule'],['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixReleaseRule',1,'Release Rule'],['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Rule',1,'STM32 Rule']]],
  ['rules_52',['Rules',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetRules',1,'Extension Rules'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Rules',1,'Update Rules']]],
  ['run_53',['Run',['../classFoundation_1_1Scheduling_1_1BasicTask.html#a78ec2045f6e42be4c8fecfca43d997cc',1,'Foundation::Scheduling::BasicTask::Run()'],['../classFoundation_1_1Scheduling_1_1BasicPeriodicTask.html#a659431590ca4b90584ada6b722c3e2a1',1,'Foundation::Scheduling::BasicPeriodicTask::Run()'],['../classFoundation_1_1Scheduling_1_1BasicOneShotTask.html#a4307395fb9f7ffda4bdd81a6184f0282',1,'Foundation::Scheduling::BasicOneShotTask::Run()']]],
  ['runnable_20example_54',['Runnable Example',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsExample',1,'Runnable Example'],['../group__Foundation__Containers.html#FoundationContainersExample',1,'Runnable Example'],['../group__Foundation__Functional.html#FoundationFunctionalExample',1,'Runnable Example'],['../group__Foundation__Scheduling.html#FoundationSchedulingExample',1,'Runnable Example']]],
  ['runnable_20examples_55',['Runnable Examples',['../group__Foundation__Time.html#FoundationTimeExamples',1,'Runnable Examples'],['../group__Foundation__Utils.html#FoundationUtilsExample',1,'Runnable Examples']]],
  ['runtime_20and_20api_20boundaries_56',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]]
];
