var searchData=
[
  ['cached_20state_0',['Cached State',['../group__Foundation__Workflows.html#FoundationWorkflowsState',1,'']]],
  ['callback_1',['Callback',['../classFoundation_1_1Functional_1_1Callback.html',1,'Foundation::Functional::Callback&lt; R, Args &gt;'],['../classFoundation_1_1Time_1_1BasicClock.html#ae8ac2acbef5c4d7f537a850a5afa8c1a',1,'Foundation::Time::BasicClock::Callback'],['../classFoundation_1_1Scheduling_1_1BasicPeriodicTask.html#a8433db7560e0a116f4ec5273ae6bbac0',1,'Foundation::Scheduling::BasicPeriodicTask::Callback'],['../classFoundation_1_1Scheduling_1_1BasicOneShotTask.html#a25f052d11bc389da2a5ad1e337cfe9c0',1,'Foundation::Scheduling::BasicOneShotTask::Callback'],['../classFoundation_1_1Functional_1_1Callback.html#a69f1e5894b5ff9c812d2f6c4b837f92a',1,'Foundation::Functional::Callback::Callback()'],['../classFoundation_1_1Functional_1_1Callback_3_01void_00_01Args_8_8_8_01_4.html#a8bf6c5e5e47f1bdffdeb76c3d2048a99',1,'Foundation::Functional::Callback&lt; void, Args... &gt;::Callback()'],['../group__Foundation__Callback.html',1,'Callback']]],
  ['callback_2eh_2',['Callback.h',['../Callback_2Callback_8h.html',1,'']]],
  ['callback_3c_20representation_20_3e_3',['Callback&lt; Representation &gt;',['../classFoundation_1_1Functional_1_1Callback.html',1,'Foundation::Functional']]],
  ['callback_3c_20void_2c_20args_2e_2e_2e_20_3e_4',['Callback&lt; void, Args... &gt;',['../classFoundation_1_1Functional_1_1Callback_3_01void_00_01Args_8_8_8_01_4.html',1,'Foundation::Functional']]],
  ['callbacktype_5',['CallbackType',['../classFoundation_1_1Functional_1_1Callback.html#a0f3c77df1c4bd68531fed3b5710b90c6',1,'Foundation::Functional::Callback::CallbackType'],['../classFoundation_1_1Functional_1_1Callback_3_01void_00_01Args_8_8_8_01_4.html#a5ca36c14ad5d53ccce0a7bb31ac8839c',1,'Foundation::Functional::Callback&lt; void, Args... &gt;::CallbackType']]],
  ['candidate_20export_6',['Release-Candidate Export',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowExport',1,'']]],
  ['categories_7',['Categories',['../group__Foundation__TypeTraits__Composite.html',1,'Composite Type Categories'],['../group__Foundation__TypeTraits__Primary.html',1,'Primary Type Categories']]],
  ['changed_8',['Changed',['../md_CHANGELOG.html#autotoc_md14',1,'Changed'],['../md_CHANGELOG.html#autotoc_md17',1,'Changed'],['../md_CHANGELOG.html#autotoc_md21',1,'Changed'],['../md_CHANGELOG.html#autotoc_md24',1,'Changed'],['../md_CHANGELOG.html#autotoc_md27',1,'Changed']]],
  ['changelog_9',['Changelog',['../md_CHANGELOG.html',1,'']]],
  ['changes_10',['Documentation Changes',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDocs',1,'']]],
  ['checklist_11',['Checklist',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewPacket',1,'Evidence Packet Checklist'],['../group__Foundation__Workflows__DesktopValidation.html',1,'Windows and macOS Checklist']]],
  ['checklist_20for_20each_20preset_12',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['checkout_13',['Checkout',['../md_README.html#autotoc_md1',1,'']]],
  ['checks_14',['Checks',['../group__Foundation__Workflows__Validation.html#FoundationValidationPackage',1,'Package Checks'],['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsQuality',1,'Quality Checks']]],
  ['chip_15',['Why not every chip',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCWhy',1,'']]],
  ['ci_20contract_16',['CI Contract',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCI',1,'CI Contract'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureCI',1,'Reusable CI Contract']]],
  ['circularbuffer_17',['CircularBuffer',['../classFoundation_1_1Containers_1_1CircularBuffer.html',1,'Foundation::Containers::CircularBuffer&lt; T &gt;'],['../classFoundation_1_1Containers_1_1CircularBuffer.html#a2abd7db5be04145a64f98b9a690b1299',1,'Foundation::Containers::CircularBuffer::CircularBuffer()']]],
  ['classes_18',['Helper Classes',['../group__Foundation__TypeTraits__Helpers.html',1,'']]],
  ['clean_19',['Clean',['../group__Foundation__Workflows__Clean.html',1,'']]],
  ['clear_20',['Clear',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a4befd89d4832a6f536d87d70cfed211c',1,'Foundation::Math::Matrix::Dynamic::Clear()'],['../classFoundation_1_1Scheduling_1_1BasicTaskScheduler.html#ae9b67413e9e3dd8b0a29aaa1a418b734',1,'Foundation::Scheduling::BasicTaskScheduler::Clear()']]],
  ['clock_21',['Clock',['../namespaceFoundation_1_1Time.html#a25045cb1545a87802a3c175cf6266c98',1,'Foundation::Time::Clock'],['../group__Foundation__Time__Clock.html',1,'Clock']]],
  ['cmake_22',['Build Through CMake',['../group__Foundation__Examples.html#FoundationExamplesBuild',1,'']]],
  ['code_20quality_23',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['coding_20style_24',['Coding Style',['../group__Foundation.html#Foundation_Style',1,'']]],
  ['collapsible_20indexes_25',['Collapsible Indexes',['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsIndexes',1,'']]],
  ['collected_26',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['columncount_27',['ColumnCount',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a8929aadfb18f5983a1125ea3b17ed769',1,'Foundation::Math::Matrix::Fixed::ColumnCount()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#ab01f1dccbc962ed4116260c9a7566185',1,'Foundation::Math::Matrix::Dynamic::ColumnCount()']]],
  ['command_20validation_28',['One-Command Validation',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCommand',1,'']]],
  ['commands_29',['Commands',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMacOS',1,'macOS Commands'],['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationWindows',1,'Windows Commands']]],
  ['common_20failures_30',['Common Failures',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildFailures',1,'']]],
  ['common_20preflight_31',['Common Preflight',['../group__Foundation__Workflows__Validation.html#FoundationValidationPreflight',1,'']]],
  ['compatibility_20matrix_32',['Compatibility Matrix',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCompatibilityMatrix',1,'']]],
  ['compatibility_20rule_33',['Compatibility Rule',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportCompatibility',1,'']]],
  ['compile_20time_20and_20exception_20contract_34',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['complete_20local_20sequence_35',['Complete Local Sequence',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRCommands',1,'']]],
  ['completed_20baseline_36',['Completed Baseline',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Baseline',1,'']]],
  ['complex_37',['Complex',['../classFoundation_1_1Math_1_1Complex.html',1,'Foundation::Math::Complex&lt; T &gt;'],['../classFoundation_1_1Math_1_1Complex.html#a5d6127f215025c06733cc0c1455bfb34',1,'Foundation::Math::Complex::Complex()'],['../classFoundation_1_1Math_1_1Complex.html#aa5638c6061df5fe43e351a10e75126e7',1,'Foundation::Math::Complex::Complex(T real)'],['../classFoundation_1_1Math_1_1Complex.html#a211479fe88317cf34ef2725b0b9d59ba',1,'Foundation::Math::Complex::Complex(T real, T imag)'],['../classFoundation_1_1Math_1_1Complex.html#ab2c7176f3f794783cf15779b196d9f3d',1,'Foundation::Math::Complex::Complex(const Complex&lt; T &gt; &amp;other)'],['../group__Foundation__Math__Complex.html',1,'Complex']]],
  ['complex_2eh_38',['Complex.h',['../Complex_2Complex_8h.html',1,'']]],
  ['complexity_39',['Computational Complexity',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsComplexity',1,'']]],
  ['components_40',['Related Components',['../group__Foundation__Callback.html#FoundationCallbackRelated',1,'']]],
  ['composite_20type_20categories_41',['Composite Type Categories',['../group__Foundation__TypeTraits__Composite.html',1,'']]],
  ['computational_20complexity_42',['Computational Complexity',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsComplexity',1,'']]],
  ['configuration_43',['Configuration',['../group__Foundation__Workflows__Configuration.html',1,'Configuration'],['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRToolchain',1,'Toolchain Configuration']]],
  ['configuration_20and_20overrides_44',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['configure_45',['Configure',['../group__Foundation__Workflows__Configure.html',1,'']]],
  ['conjugate_46',['Conjugate',['../classFoundation_1_1Math_1_1Complex.html#a14de8d782816682154225c952e8f0ca5',1,'Foundation::Math::Complex']]],
  ['consistency_47',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['construction_48',['Construction',['../group__Foundation__Matrix__Fixed.html#FoundationFixedConstruction',1,'']]],
  ['consumer_49',['Installed Package Consumer',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPackageConsumer',1,'']]],
  ['consumer_20—_202026_2009_2027_50',['Published v1.2.0 downstream consumer — 2026-09-27',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceReleasedConsumer',1,'']]],
  ['consumer_20—_202026_2009_2028_51',['STM32G0B1CBT6 firmware consumer — 2026-09-28',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceSTM32G0B1',1,'']]],
  ['consumer_20contract_52',['Consumer Contract',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledConsumer',1,'']]],
  ['consumer_20on_20an_20arduino_20uno_20—_202026_2009_2026_53',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['consumer_20validation_54',['Consumer Validation',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRConsumer',1,'Consumer Validation'],['../group__Foundation__Workflows__PackageConsumer.html',1,'Package Consumer Validation']]],
  ['consuming_20a_20download_55',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['container_20types_56',['Container Types',['../group__Foundation__Containers.html#FoundationContainersTypes',1,'']]],
  ['containers_57',['Containers',['../group__Foundation__Containers.html',1,'Containers'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageContainers',1,'Containers']]],
  ['containers_20module_58',['Containers Module',['../group__Foundation.html#Foundation_ContainersModule',1,'']]],
  ['continuous_20integration_59',['Continuous Integration',['../group__Foundation__Workflows__ContinuousIntegration.html',1,'Continuous Integration'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M2',1,'M2 - Continuous Integration']]],
  ['contract_60',['Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'Build and Include Contract'],['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCI',1,'CI Contract'],['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'Compile-Time and Exception Contract'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledConsumer',1,'Consumer Contract'],['../group__Foundation__TypeTraits.html#FoundationTypeTraitsContract',1,'Current Contract'],['../group__Foundation__Functional.html#FoundationFunctionalContract',1,'Current Contract'],['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicFailure',1,'Failure Contract'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M1',1,'M1 - Release Contract'],['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'Ownership and Timing Contract'],['../group__Foundation__Examples.html#FoundationExamplesPresentation',1,'Presentation Contract'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructurePresetContract',1,'Preset and Toolchain Contract'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureCI',1,'Reusable CI Contract'],['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'Storage and Lifetime Contract'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureWorkflowAdapter',1,'Workflow Adapter Contract']]],
  ['copy_61',['Copy',['../group__Foundation__Utils.html#gacc170552c42db70106fb5acc7faebebc',1,'Foundation::Utils::Flash']]],
  ['copystring_62',['CopyString',['../group__Foundation__Utils.html#ga88661d84fd276d68cd14e61149b05fd3',1,'Foundation::Utils::Flash']]],
  ['counsel_63',['Questions for Counsel',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCounsel',1,'']]],
  ['coverage_64',['Coverage',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationCoverage',1,'Coverage'],['../group__Foundation__Workflows__PublicApiCoverage.html',1,'Public API Coverage'],['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsValidation',1,'Validation Coverage']]],
  ['creator_20usage_65',['PSoC Creator Usage',['../group__Foundation.html#FoundationTop_PSoCUsage',1,'']]],
  ['criteria_66',['Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'Acceptance Criteria'],['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewExit',1,'Exit Criteria'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditExit',1,'Freeze Exit Criteria']]],
  ['cross_20outputs_67',['Inspecting Cross Outputs',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowToolchainInspect',1,'']]],
  ['cross_20tests_68',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['current_20contract_69',['Current Contract',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsContract',1,'Current Contract'],['../group__Foundation__Functional.html#FoundationFunctionalContract',1,'Current Contract']]],
  ['current_20position_70',['Current Position',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCurrent',1,'']]],
  ['custom_20build_71',['Custom Build',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCustomBuild',1,'']]],
  ['custom_20precompiled_20mode_72',['Custom Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'']]]
];
