var searchData=
[
  ['cached_20state_0',['Cached State',['../group__Foundation__Workflows.html#FoundationWorkflowsState',1,'']]],
  ['callback_1',['Callback',['../classFoundation_1_1Functional_1_1Callback.html',1,'Foundation::Functional::Callback&lt; R, Args &gt;'],['../classFoundation_1_1Time_1_1BasicClock.html#ae8ac2acbef5c4d7f537a850a5afa8c1a',1,'Foundation::Time::BasicClock::Callback'],['../classFoundation_1_1Scheduling_1_1BasicPeriodicTask.html#a8433db7560e0a116f4ec5273ae6bbac0',1,'Foundation::Scheduling::BasicPeriodicTask::Callback'],['../classFoundation_1_1Scheduling_1_1BasicOneShotTask.html#a25f052d11bc389da2a5ad1e337cfe9c0',1,'Foundation::Scheduling::BasicOneShotTask::Callback'],['../classFoundation_1_1Functional_1_1Callback.html#a69f1e5894b5ff9c812d2f6c4b837f92a',1,'Foundation::Functional::Callback::Callback()'],['../classFoundation_1_1Functional_1_1Callback_3_01void_00_01Args_8_8_8_01_4.html#a8bf6c5e5e47f1bdffdeb76c3d2048a99',1,'Foundation::Functional::Callback&lt; void, Args... &gt;::Callback()'],['../group__Foundation__Callback.html',1,'Callback']]],
  ['callback_2eh_2',['Callback.h',['../Callback_2Callback_8h.html',1,'']]],
  ['callback_3c_20representation_20_3e_3',['Callback&lt; Representation &gt;',['../classFoundation_1_1Functional_1_1Callback.html',1,'Foundation::Functional']]],
  ['callback_3c_20void_2c_20args_2e_2e_2e_20_3e_4',['Callback&lt; void, Args... &gt;',['../classFoundation_1_1Functional_1_1Callback_3_01void_00_01Args_8_8_8_01_4.html',1,'Foundation::Functional']]],
  ['callbacktype_5',['CallbackType',['../classFoundation_1_1Functional_1_1Callback.html#a0f3c77df1c4bd68531fed3b5710b90c6',1,'Foundation::Functional::Callback::CallbackType'],['../classFoundation_1_1Functional_1_1Callback_3_01void_00_01Args_8_8_8_01_4.html#a5ca36c14ad5d53ccce0a7bb31ac8839c',1,'Foundation::Functional::Callback&lt; void, Args... &gt;::CallbackType']]],
  ['candidate_20export_6',['Release-Candidate Export',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowExport',1,'']]],
  ['categories_7',['Categories',['../group__Foundation__TypeTraits__Composite.html',1,'Composite Type Categories'],['../group__Foundation__TypeTraits__Primary.html',1,'Primary Type Categories']]],
  ['changed_8',['Changed',['../md_CHANGELOG.html#autotoc_md10',1,'Changed'],['../md_CHANGELOG.html#autotoc_md14',1,'Changed'],['../md_CHANGELOG.html#autotoc_md17',1,'Changed'],['../md_CHANGELOG.html#autotoc_md20',1,'Changed']]],
  ['changelog_9',['Changelog',['../md_CHANGELOG.html',1,'']]],
  ['changes_10',['Documentation Changes',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDocs',1,'']]],
  ['checklist_11',['Checklist',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewPacket',1,'Evidence Packet Checklist'],['../group__Foundation__Workflows__DesktopValidation.html',1,'Windows and macOS Checklist']]],
  ['checklist_20for_20each_20preset_12',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['checks_13',['Checks',['../group__Foundation__Workflows__Validation.html#FoundationValidationPackage',1,'Package Checks'],['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsQuality',1,'Quality Checks']]],
  ['chip_14',['Why not every chip',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCWhy',1,'']]],
  ['ci_20contract_15',['CI Contract',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCI',1,'']]],
  ['circularbuffer_16',['CircularBuffer',['../classFoundation_1_1Containers_1_1CircularBuffer.html',1,'Foundation::Containers::CircularBuffer&lt; T &gt;'],['../classFoundation_1_1Containers_1_1CircularBuffer.html#a2abd7db5be04145a64f98b9a690b1299',1,'Foundation::Containers::CircularBuffer::CircularBuffer()']]],
  ['classes_17',['Helper Classes',['../group__Foundation__TypeTraits__Helpers.html',1,'']]],
  ['clean_18',['Clean',['../group__Foundation__Workflows__Clean.html',1,'']]],
  ['clear_19',['Clear',['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#a4befd89d4832a6f536d87d70cfed211c',1,'Foundation::Math::Matrix::Dynamic::Clear()'],['../classFoundation_1_1Scheduling_1_1BasicTaskScheduler.html#ae9b67413e9e3dd8b0a29aaa1a418b734',1,'Foundation::Scheduling::BasicTaskScheduler::Clear()']]],
  ['clock_20',['Clock',['../namespaceFoundation_1_1Time.html#a25045cb1545a87802a3c175cf6266c98',1,'Foundation::Time::Clock'],['../group__Foundation__Time__Clock.html',1,'Clock']]],
  ['cmake_21',['Build Through CMake',['../group__Foundation__Examples.html#FoundationExamplesBuild',1,'']]],
  ['code_20quality_22',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['coding_20style_23',['Coding Style',['../group__Foundation.html#Foundation_Style',1,'']]],
  ['collapsible_20indexes_24',['Collapsible Indexes',['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsIndexes',1,'']]],
  ['collected_25',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['columncount_26',['ColumnCount',['../classFoundation_1_1Math_1_1Matrix_1_1Fixed.html#a8929aadfb18f5983a1125ea3b17ed769',1,'Foundation::Math::Matrix::Fixed::ColumnCount()'],['../classFoundation_1_1Math_1_1Matrix_1_1Dynamic.html#ab01f1dccbc962ed4116260c9a7566185',1,'Foundation::Math::Matrix::Dynamic::ColumnCount()']]],
  ['command_20validation_27',['One-Command Validation',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCommand',1,'']]],
  ['commands_28',['Commands',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMacOS',1,'macOS Commands'],['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationWindows',1,'Windows Commands']]],
  ['common_20failures_29',['Common Failures',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildFailures',1,'']]],
  ['common_20preflight_30',['Common Preflight',['../group__Foundation__Workflows__Validation.html#FoundationValidationPreflight',1,'']]],
  ['compatibility_20matrix_31',['Compatibility Matrix',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCompatibilityMatrix',1,'']]],
  ['compatibility_20rule_32',['Compatibility Rule',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportCompatibility',1,'']]],
  ['compile_20time_20and_20exception_20contract_33',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['complete_20local_20sequence_34',['Complete Local Sequence',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRCommands',1,'']]],
  ['completed_20baseline_35',['Completed Baseline',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Baseline',1,'']]],
  ['complex_36',['Complex',['../classFoundation_1_1Math_1_1Complex.html',1,'Foundation::Math::Complex&lt; T &gt;'],['../classFoundation_1_1Math_1_1Complex.html#a5d6127f215025c06733cc0c1455bfb34',1,'Foundation::Math::Complex::Complex()'],['../classFoundation_1_1Math_1_1Complex.html#aa5638c6061df5fe43e351a10e75126e7',1,'Foundation::Math::Complex::Complex(T real)'],['../classFoundation_1_1Math_1_1Complex.html#a211479fe88317cf34ef2725b0b9d59ba',1,'Foundation::Math::Complex::Complex(T real, T imag)'],['../classFoundation_1_1Math_1_1Complex.html#ab2c7176f3f794783cf15779b196d9f3d',1,'Foundation::Math::Complex::Complex(const Complex&lt; T &gt; &amp;other)'],['../group__Foundation__Math__Complex.html',1,'Complex']]],
  ['complex_2eh_37',['Complex.h',['../Complex_2Complex_8h.html',1,'']]],
  ['complexity_38',['Computational Complexity',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsComplexity',1,'']]],
  ['components_39',['Related Components',['../group__Foundation__Callback.html#FoundationCallbackRelated',1,'']]],
  ['composite_20type_20categories_40',['Composite Type Categories',['../group__Foundation__TypeTraits__Composite.html',1,'']]],
  ['computational_20complexity_41',['Computational Complexity',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsComplexity',1,'']]],
  ['configuration_42',['Configuration',['../group__Foundation__Workflows__Configuration.html',1,'Configuration'],['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRToolchain',1,'Toolchain Configuration']]],
  ['configuration_20and_20overrides_43',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['configure_44',['Configure',['../group__Foundation__Workflows__Configure.html',1,'']]],
  ['conjugate_45',['Conjugate',['../classFoundation_1_1Math_1_1Complex.html#a14de8d782816682154225c952e8f0ca5',1,'Foundation::Math::Complex']]],
  ['consistency_46',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['construction_47',['Construction',['../group__Foundation__Matrix__Fixed.html#FoundationFixedConstruction',1,'']]],
  ['consumer_48',['Installed Package Consumer',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPackageConsumer',1,'']]],
  ['consumer_20contract_49',['Consumer Contract',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledConsumer',1,'']]],
  ['consumer_20validation_50',['Consumer Validation',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRConsumer',1,'Consumer Validation'],['../group__Foundation__Workflows__PackageConsumer.html',1,'Package Consumer Validation']]],
  ['consuming_20a_20download_51',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['container_20types_52',['Container Types',['../group__Foundation__Containers.html#FoundationContainersTypes',1,'']]],
  ['containers_53',['Containers',['../group__Foundation__Containers.html',1,'Containers'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageContainers',1,'Containers']]],
  ['containers_20module_54',['Containers Module',['../group__Foundation.html#Foundation_ContainersModule',1,'']]],
  ['continuous_20integration_55',['Continuous Integration',['../group__Foundation__Workflows__ContinuousIntegration.html',1,'Continuous Integration'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M2',1,'M2 - Continuous Integration']]],
  ['contract_56',['Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'Build and Include Contract'],['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCI',1,'CI Contract'],['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'Compile-Time and Exception Contract'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledConsumer',1,'Consumer Contract'],['../group__Foundation__TypeTraits.html#FoundationTypeTraitsContract',1,'Current Contract'],['../group__Foundation__Functional.html#FoundationFunctionalContract',1,'Current Contract'],['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicFailure',1,'Failure Contract'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M1',1,'M1 - Release Contract'],['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'Ownership and Timing Contract'],['../group__Foundation__Examples.html#FoundationExamplesPresentation',1,'Presentation Contract'],['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'Storage and Lifetime Contract']]],
  ['counsel_57',['Questions for Counsel',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCounsel',1,'']]],
  ['coverage_58',['Coverage',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationCoverage',1,'Coverage'],['../group__Foundation__Workflows__PublicApiCoverage.html',1,'Public API Coverage'],['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsValidation',1,'Validation Coverage']]],
  ['creator_20usage_59',['PSoC Creator Usage',['../group__Foundation.html#FoundationTop_PSoCUsage',1,'']]],
  ['criteria_60',['Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'Acceptance Criteria'],['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewExit',1,'Exit Criteria'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditExit',1,'Freeze Exit Criteria']]],
  ['cross_20outputs_61',['Inspecting Cross Outputs',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowToolchainInspect',1,'']]],
  ['cross_20tests_62',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['current_20contract_63',['Current Contract',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsContract',1,'Current Contract'],['../group__Foundation__Functional.html#FoundationFunctionalContract',1,'Current Contract']]],
  ['current_20position_64',['Current Position',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCurrent',1,'']]],
  ['custom_20build_65',['Custom Build',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCustomBuild',1,'']]],
  ['custom_20precompiled_20mode_66',['Custom Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'']]]
];
