var searchData=
[
  ['target_0',['Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'Adding a Target'],['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRTarget',1,'Initial Supported Target']]],
  ['target_20architecture_1',['Target Architecture',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureArchitecture',1,'']]],
  ['target_20only_20evidence_2',['Target-only Evidence',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageTarget',1,'']]],
  ['target_20platforms_3',['Target Platforms',['../group__Foundation.html#Foundation_TargetPlatforms',1,'']]],
  ['target_20platforms_20and_20support_20status_4',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['target_20profile_5',['Experimental Target Profile',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCTarget',1,'']]],
  ['targets_6',['Targets',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixEmbedded',1,'Named Embedded Targets'],['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixDesktop',1,'Native Desktop Targets']]],
  ['test_20depth_20and_20code_20quality_7',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['test_20status_8',['Test Status',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsTests',1,'']]],
  ['test_20suite_20scope_9',['Test-Suite Scope',['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'']]],
  ['test_20work_10',['Prioritized Test Work',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageNext',1,'']]],
  ['tests_11',['Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'Native and Cross Tests'],['../md_README.html#autotoc_md4',1,'Tests']]],
  ['tests_20and_20examples_12',['Tests and Examples',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowTests',1,'']]],
  ['the_20result_13',['Inspecting the Result',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureInspect',1,'']]],
  ['through_20cmake_14',['Build Through CMake',['../group__Foundation__Examples.html#FoundationExamplesBuild',1,'']]],
  ['through_20rosetta_202_20—_202026_2009_2026_15',['macOS x86-64 through Rosetta 2 — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSx64',1,'']]],
  ['tick_20representations_16',['Tick Representations',['../group__Foundation__Time.html#FoundationTimeRepresentations',1,'']]],
  ['tick_20type_20consistency_17',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['time_18',['Time',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageTime',1,'']]],
  ['time_20and_20exception_20contract_19',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['time_20and_20validity_20',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['time_20module_21',['Time Module',['../group__Foundation.html#Foundation_TimeModule',1,'']]],
  ['timing_20contract_22',['Ownership and Timing Contract',['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'']]],
  ['to_20use_20fresh_23',['When to Use Fresh',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureFresh',1,'']]],
  ['toolchain_20configuration_24',['Toolchain Configuration',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRToolchain',1,'']]],
  ['toolchain_20contract_25',['Preset and Toolchain Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructurePresetContract',1,'']]],
  ['toolchains_26',['Supported Windows Toolchains',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsToolchains',1,'']]],
  ['top_20level_20header_20list_27',['Top-Level Header List',['../group__Foundation.html#FoundationTop_HeaderList',1,'']]],
  ['top_20level_20headers_28',['Top-Level Headers',['../group__Foundation.html',1,'']]],
  ['topics_29',['Related Topics',['../group__Foundation.html#FoundationTop_RelatedTopics',1,'']]],
  ['trait_20families_30',['Trait Families',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsFamilies',1,'']]],
  ['traits_20module_31',['Type Traits Module',['../group__Foundation.html#Foundation_TypeTraitsModule',1,'']]],
  ['transpose_32',['Transpose',['../group__Foundation__Matrix__Fixed.html#FoundationFixedTranspose',1,'']]],
  ['triggers_20and_20permissions_33',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['triggers_20and_20publication_34',['Triggers and Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'']]],
  ['type_20consistency_35',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['type_20traits_20module_36',['Type Traits Module',['../group__Foundation.html#Foundation_TypeTraitsModule',1,'']]],
  ['types_37',['Types',['../group__Foundation__Containers.html#FoundationContainersTypes',1,'Container Types'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageLegend',1,'Evidence Types'],['../group__Foundation__Matrix.html#FoundationMatrixTypes',1,'Matrix Types'],['../group__Foundation__Time.html#FoundationTimeTypes',1,'Public Types'],['../group__Foundation__Scheduling.html#FoundationSchedulingTypes',1,'Public Types']]],
  ['typetraits_38',['TypeTraits',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageTypeTraits',1,'']]],
  ['typetraits_20basicchecks_39',['TypeTraits BasicChecks',['../group__Foundation__Examples.html#FoundationExamplesTypeTraits',1,'']]],
  ['typetraits_20evidence_40',['TypeTraits Evidence',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditTraitEvidence',1,'']]]
];
