var searchData=
[
  ['daily_20development_0',['Daily Development',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDaily',1,'']]],
  ['data_1',['Program-Memory Data',['../group__Foundation__Utils.html#FoundationUtilsFlash',1,'']]],
  ['decision_2',['Decision',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCStatus',1,'1.x Status Decision'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureStatus',1,'Status and Decision']]],
  ['decisions_3',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['defaults_4',['Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['dependencies_5',['Dependencies',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureDependencies',1,'Feature Dependencies'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditDependencies',1,'Module Dependencies']]],
  ['dependency_6',['GoogleTest Dependency',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestDependency',1,'']]],
  ['dependency_20model_7',['Dependency Model',['../group__Foundation.html#Foundation_DependencyModel',1,'']]],
  ['dependency_20roadmap_8',['Dependency Roadmap',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Roadmap',1,'']]],
  ['deprecated_20list_9',['Deprecated List',['../deprecated.html',1,'']]],
  ['depth_20and_20code_20quality_10',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['design_20goals_11',['Design Goals',['../group__Foundation.html#Foundation_DesignGoals',1,'Design Goals'],['../index.html#MainPage_DesignGoals',1,'Design Goals']]],
  ['desktop_20matrix_12',['Desktop Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationDesktop',1,'']]],
  ['desktop_20targets_13',['Native Desktop Targets',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixDesktop',1,'']]],
  ['desktop_20usage_14',['Desktop Usage',['../group__Foundation.html#FoundationTop_DesktopUsage',1,'']]],
  ['development_15',['Development',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildExamples',1,'Building Examples for Development'],['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDaily',1,'Daily Development']]],
  ['directories_16',['Workflow Directories',['../group__Foundation__Workflows.html#FoundationWorkflowsDirectories',1,'']]],
  ['distribution_20and_20pinning_17',['Distribution and Pinning',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureDistribution',1,'']]],
  ['documentation_18',['Foundation Documentation',['../index.html',1,'']]],
  ['documentation_20changes_19',['Documentation Changes',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDocs',1,'']]],
  ['documentation_20layout_20',['Documentation Layout',['../group__Foundation.html#Foundation_DocumentationLayout',1,'']]],
  ['documentation_20validation_21',['Documentation Validation',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationDocumentation',1,'']]],
  ['download_22',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['downstream_20consumer_20—_202026_2009_2027_23',['Published v1.2.0 downstream consumer — 2026-09-27',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceReleasedConsumer',1,'']]],
  ['dynamic_20matrices_24',['Dynamic Matrices',['../group__Foundation__Matrix.html#FoundationMatrixDynamic',1,'Dynamic Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsDynamic',1,'Dynamic Matrices']]],
  ['dynamic_20memory_25',['Dynamic Memory',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRMemory',1,'']]]
];
