var searchData=
[
  ['a_20download_0',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['a_20target_1',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['acceptance_20and_20evidence_2',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['acceptance_20criteria_3',['Acceptance Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'']]],
  ['access_4',['Element Access',['../group__Foundation__Matrix__Fixed.html#FoundationFixedElementAccess',1,'']]],
  ['added_5',['Added',['../md_CHANGELOG.html#autotoc_md9',1,'Added'],['../md_CHANGELOG.html#autotoc_md13',1,'Added'],['../md_CHANGELOG.html#autotoc_md16',1,'Added'],['../md_CHANGELOG.html#autotoc_md19',1,'Added']]],
  ['adding_20a_20target_6',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['adding_20an_20example_7',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['aliasing_8',['Aliasing',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicAliasing',1,'']]],
  ['an_20example_9',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['an_20existing_20package_10',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['anatomy_11',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['and_20api_20boundaries_12',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['and_20code_20quality_13',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['and_20cross_20tests_14',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['and_20defaults_15',['and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['and_20evidence_16',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['and_20examples_17',['Tests and Examples',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowTests',1,'']]],
  ['and_20exception_20contract_18',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['and_20export_19',['Build and Export',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Commands',1,'']]],
  ['and_20hardware_20validation_20',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['and_20include_20contract_21',['Build and Include Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'']]],
  ['and_20installation_22',['Build and Installation',['../index.html#MainPage_Build',1,'']]],
  ['and_20license_20status_23',['Release and License Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'']]],
  ['and_20lifetime_24',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['and_20lifetime_20contract_25',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['and_20overrides_26',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['and_20permissions_27',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['and_20publication_28',['Triggers and Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'']]],
  ['and_20sanitizers_29',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['and_20scope_30',['Method and Scope',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'']]],
  ['and_20support_20status_31',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['and_20timing_20contract_32',['Ownership and Timing Contract',['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'']]],
  ['and_20validity_33',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['and_20workflow_20hardening_34',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['api_35',['API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['api_20boundaries_36',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['api_20policy_37',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['applications_38',['Applications',['../group__Foundation__Matrix.html#FoundationMatrixApplications',1,'Applications'],['../group__Foundation__Matrix__Fixed.html#FoundationFixedApplications',1,'Applications'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsApplications',1,'Applications']]],
  ['architecture_39',['Module Architecture',['../group__Foundation.html#Foundation_ModuleArchitecture',1,'']]],
  ['arduino_40',['Arduino',['../md_README.html#autotoc_md5',1,'']]],
  ['arduino_20libraries_41',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['arduino_20usage_42',['Arduino Usage',['../group__Foundation.html#FoundationTop_ArduinoUsage',1,'']]],
  ['arguments_20and_20defaults_43',['Arguments and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['arithmetic_20operations_44',['Arithmetic Operations',['../group__Foundation__Matrix__Fixed.html#FoundationFixedArithmetic',1,'']]],
  ['arm_20bare_20metal_20local_20preflight_20—_202026_2009_2025_45',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['arm_20embedded_46',['GNU Arm Embedded',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowArmToolchain',1,'']]],
  ['arm_20profiles_47',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['arm64_20—_202026_2009_2025_48',['macOS Arm64 — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64',1,'']]],
  ['as_20executables_49',['Export as Executables',['../group__Foundation__Examples.html#FoundationExamplesExport',1,'']]],
  ['atmega328p_20—_202026_2009_2025_50',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['availability_51',['Module Availability',['../group__Foundation.html#FoundationTop_ModuleAvailability',1,'']]],
  ['available_20native_20examples_52',['Available Native Examples',['../group__Foundation__Examples.html#FoundationExamplesAvailable',1,'']]],
  ['avr_20atmega328p_20—_202026_2009_2025_53',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['avr_20gcc_54',['AVR-GCC',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAVRToolchain',1,'']]],
  ['avr_20matrix_55',['AVR Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationAVR',1,'']]]
];
