var searchData=
[
  ['sanitizers_0',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['scheduling_1',['Scheduling',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageScheduling',1,'']]],
  ['scheduling_20module_2',['Scheduling Module',['../group__Foundation.html#Foundation_SchedulingModule',1,'']]],
  ['scope_3',['Scope',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Scope',1,'Library Scope'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'Method and Scope'],['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPlatforms',1,'Platform Scope'],['../group__Foundation__Workflows__Clean.html#FoundationWorkflowCleanScope',1,'Scope'],['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'Test-Suite Scope']]],
  ['sections_4',['Sections',['../group__Foundation__BuildGuide.html#FoundationBuildGuideSections',1,'']]],
  ['selective_20include_5',['Selective Include',['../group__Foundation.html#FoundationTop_SelectiveInclude',1,'']]],
  ['sequence_6',['Sequence',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRCommands',1,'Complete Local Sequence'],['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationSequence',1,'Job Sequence'],['../group__Foundation__Workflows.html#FoundationWorkflowsSequence',1,'Normal Release Sequence']]],
  ['set_20matrix_7',['Feature-Set Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'']]],
  ['settings_20header_8',['Build Settings Header',['../group__Foundation.html#FoundationTop_BuildSettingsHeader',1,'']]],
  ['severity_9',['Severity',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditSeverity',1,'']]],
  ['signature_20model_10',['Signature Model',['../group__Foundation__Callback.html#FoundationCallbackSignatures',1,'']]],
  ['source_20mode_11',['Source Mode',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoSource',1,'Source Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildSourceMode',1,'Source Mode']]],
  ['source_20mode_20integrations_12',['Source-Mode Integrations',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixSourceMode',1,'']]],
  ['started_13',['Getting Started',['../index.html#MainPage_GettingStarted',1,'']]],
  ['state_14',['Cached State',['../group__Foundation__Workflows.html#FoundationWorkflowsState',1,'']]],
  ['state_20and_20lifetime_15',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['status_16',['Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'Release and License Status'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditStatus',1,'Status'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageStatus',1,'Status'],['../index.html#MainPage_Platforms',1,'Target Platforms and Support Status'],['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsTests',1,'Test Status']]],
  ['status_20and_20decision_17',['Status and Decision',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureStatus',1,'']]],
  ['status_20decision_18',['1.x Status Decision',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCStatus',1,'']]],
  ['status_20header_19',['Status Header',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Status',1,'']]],
  ['steps_20',['Next Steps',['../index.html#MainPage_NextSteps',1,'']]],
  ['still_20open_21',['Quality Gates Still Open',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsQuality',1,'']]],
  ['stm32_20matrix_22',['STM32 Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationSTM32',1,'']]],
  ['stm32_20rule_23',['STM32 Rule',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Rule',1,'']]],
  ['stm32g0b1_20hardware_20acceptance_24',['STM32G0B1 Hardware Acceptance',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32G0Hardware',1,'']]],
  ['stm32g0b1cbt6_20firmware_20consumer_20—_202026_2009_2028_25',['STM32G0B1CBT6 firmware consumer — 2026-09-28',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceSTM32G0B1',1,'']]],
  ['storage_26',['External Storage',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicExternalStorage',1,'']]],
  ['storage_20and_20lifetime_20contract_27',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['strategies_28',['Include Strategies',['../group__Foundation.html#FoundationTop_IncludeStrategies',1,'']]],
  ['structure_29',['Group Structure',['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsStructure',1,'']]],
  ['style_30',['Coding Style',['../group__Foundation.html#Foundation_Style',1,'']]],
  ['suite_31',['Registered Native Suite',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestSuite',1,'']]],
  ['suite_20scope_32',['Test-Suite Scope',['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'']]],
  ['superseded_20before_20publication_33',['[1.0.0] - Superseded before publication',['../md_CHANGELOG.html#autotoc_md38',1,'']]],
  ['support_20levels_34',['Support Levels',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixLevels',1,'']]],
  ['support_20status_35',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['supported_20families_36',['Supported Families',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFamilies',1,'']]],
  ['supported_20target_37',['Initial Supported Target',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRTarget',1,'']]],
  ['supported_20windows_20toolchains_38',['Supported Windows Toolchains',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsToolchains',1,'']]],
  ['surface_20inventory_39',['Public Surface Inventory',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditInventory',1,'']]],
  ['sustained_201_20x_20releases_40',['M6 - Sustained 1.x Releases',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M6',1,'']]],
  ['system_41',['Build System',['../group__Foundation.html#Foundation_BuildSystem',1,'']]]
];
