var searchData=
[
  ['cached_20state_0',['Cached State',['../group__Foundation__Workflows.html#FoundationWorkflowsState',1,'']]],
  ['candidate_20export_1',['Release-Candidate Export',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowExport',1,'']]],
  ['changed_2',['Changed',['../md_CHANGELOG.html#autotoc_md10',1,'Changed'],['../md_CHANGELOG.html#autotoc_md14',1,'Changed'],['../md_CHANGELOG.html#autotoc_md17',1,'Changed'],['../md_CHANGELOG.html#autotoc_md20',1,'Changed']]],
  ['changelog_3',['Changelog',['../md_CHANGELOG.html',1,'']]],
  ['changes_4',['Documentation Changes',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowDocs',1,'']]],
  ['checklist_5',['Evidence Packet Checklist',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewPacket',1,'']]],
  ['checklist_20for_20each_20preset_6',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['checks_7',['Checks',['../group__Foundation__Workflows__Validation.html#FoundationValidationPackage',1,'Package Checks'],['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsQuality',1,'Quality Checks']]],
  ['chip_8',['Why not every chip',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCWhy',1,'']]],
  ['ci_20contract_9',['CI Contract',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCI',1,'']]],
  ['cmake_10',['Build Through CMake',['../group__Foundation__Examples.html#FoundationExamplesBuild',1,'']]],
  ['code_20quality_11',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['coding_20style_12',['Coding Style',['../group__Foundation.html#Foundation_Style',1,'']]],
  ['collapsible_20indexes_13',['Collapsible Indexes',['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsIndexes',1,'']]],
  ['collected_14',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['command_20validation_15',['One-Command Validation',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCommand',1,'']]],
  ['commands_16',['Commands',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMacOS',1,'macOS Commands'],['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationWindows',1,'Windows Commands']]],
  ['common_20failures_17',['Common Failures',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildFailures',1,'']]],
  ['common_20preflight_18',['Common Preflight',['../group__Foundation__Workflows__Validation.html#FoundationValidationPreflight',1,'']]],
  ['compatibility_20matrix_19',['Compatibility Matrix',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCompatibilityMatrix',1,'']]],
  ['compatibility_20rule_20',['Compatibility Rule',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportCompatibility',1,'']]],
  ['compile_20time_20and_20exception_20contract_21',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['complete_20local_20sequence_22',['Complete Local Sequence',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRCommands',1,'']]],
  ['completed_20baseline_23',['Completed Baseline',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Baseline',1,'']]],
  ['complexity_24',['Computational Complexity',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsComplexity',1,'']]],
  ['components_25',['Related Components',['../group__Foundation__Callback.html#FoundationCallbackRelated',1,'']]],
  ['computational_20complexity_26',['Computational Complexity',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsComplexity',1,'']]],
  ['configuration_27',['Toolchain Configuration',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRToolchain',1,'']]],
  ['configuration_20and_20overrides_28',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['consistency_29',['Tick-Type Consistency',['../group__Foundation__Scheduling.html#FoundationSchedulingTickTypes',1,'']]],
  ['construction_30',['Construction',['../group__Foundation__Matrix__Fixed.html#FoundationFixedConstruction',1,'']]],
  ['consumer_31',['Installed Package Consumer',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPackageConsumer',1,'']]],
  ['consumer_20contract_32',['Consumer Contract',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledConsumer',1,'']]],
  ['consumer_20validation_33',['Consumer Validation',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRConsumer',1,'']]],
  ['consuming_20a_20download_34',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['container_20types_35',['Container Types',['../group__Foundation__Containers.html#FoundationContainersTypes',1,'']]],
  ['containers_36',['Containers',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageContainers',1,'']]],
  ['containers_20module_37',['Containers Module',['../group__Foundation.html#Foundation_ContainersModule',1,'']]],
  ['continuous_20integration_38',['M2 - Continuous Integration',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M2',1,'']]],
  ['contract_39',['Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'Build and Include Contract'],['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCI',1,'CI Contract'],['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'Compile-Time and Exception Contract'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledConsumer',1,'Consumer Contract'],['../group__Foundation__TypeTraits.html#FoundationTypeTraitsContract',1,'Current Contract'],['../group__Foundation__Functional.html#FoundationFunctionalContract',1,'Current Contract'],['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicFailure',1,'Failure Contract'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M1',1,'M1 - Release Contract'],['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'Ownership and Timing Contract'],['../group__Foundation__Examples.html#FoundationExamplesPresentation',1,'Presentation Contract'],['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'Storage and Lifetime Contract']]],
  ['counsel_40',['Questions for Counsel',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCounsel',1,'']]],
  ['coverage_41',['Coverage',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationCoverage',1,'Coverage'],['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsValidation',1,'Validation Coverage']]],
  ['creator_20usage_42',['PSoC Creator Usage',['../group__Foundation.html#FoundationTop_PSoCUsage',1,'']]],
  ['criteria_43',['Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'Acceptance Criteria'],['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewExit',1,'Exit Criteria'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditExit',1,'Freeze Exit Criteria']]],
  ['cross_20outputs_44',['Inspecting Cross Outputs',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowToolchainInspect',1,'']]],
  ['cross_20tests_45',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['current_20contract_46',['Current Contract',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsContract',1,'Current Contract'],['../group__Foundation__Functional.html#FoundationFunctionalContract',1,'Current Contract']]],
  ['current_20position_47',['Current Position',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCurrent',1,'']]],
  ['custom_20build_48',['Custom Build',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCustomBuild',1,'']]],
  ['custom_20precompiled_20mode_49',['Custom Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'']]]
];
