var searchData=
[
  ['package_0',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['package_20and_20workflow_20hardening_1',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['package_20boundaries_2',['Package Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPackages',1,'']]],
  ['package_20checks_3',['Package Checks',['../group__Foundation__Workflows__Validation.html#FoundationValidationPackage',1,'']]],
  ['package_20consumer_4',['Installed Package Consumer',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPackageConsumer',1,'']]],
  ['package_20identity_20—_202026_2009_2026_5',['Package identity — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidencePackageIdentity',1,'']]],
  ['package_20layout_6',['Package Layout',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportLayout',1,'']]],
  ['package_20matrix_7',['Package Matrix',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesMatrix',1,'']]],
  ['packet_20checklist_8',['Evidence Packet Checklist',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewPacket',1,'']]],
  ['pages_9',['Related Pages',['../group__Foundation.html#Foundation_RelatedPages',1,'']]],
  ['permissions_10',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['pinning_11',['Distribution and Pinning',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureDistribution',1,'']]],
  ['plan_12',['Migration Plan',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureMigration',1,'']]],
  ['platform_20and_20hardware_20validation_13',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['platform_20scope_14',['Platform Scope',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPlatforms',1,'']]],
  ['platforms_15',['Target Platforms',['../group__Foundation.html#Foundation_TargetPlatforms',1,'']]],
  ['platforms_20and_20support_20status_16',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['policy_17',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['position_18',['Current Position',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCurrent',1,'']]],
  ['powershell_19',['PowerShell',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigurePowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Install.html#FoundationWorkflowInstallPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Clean.html#FoundationWorkflowCleanPowerShell',1,'PowerShell']]],
  ['precompiled_20arduino_20libraries_20',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['precompiled_20mode_21',['Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'Custom Precompiled Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'Full Precompiled Mode']]],
  ['preflight_22',['Common Preflight',['../group__Foundation__Workflows__Validation.html#FoundationValidationPreflight',1,'']]],
  ['preflight_20—_202026_2009_2025_23',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['prerequisites_24',['Prerequisites',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPrerequisites',1,'']]],
  ['presentation_20contract_25',['Presentation Contract',['../group__Foundation__Examples.html#FoundationExamplesPresentation',1,'']]],
  ['preset_26',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['preset_20anatomy_27',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['preset_20and_20toolchain_20contract_28',['Preset and Toolchain Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructurePresetContract',1,'']]],
  ['presets_29',['Workflow-Only Presets',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixWorkflowPresets',1,'']]],
  ['prioritized_20test_20work_30',['Prioritized Test Work',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageNext',1,'']]],
  ['procedure_31',['Release Procedure',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesReleaseProcedure',1,'']]],
  ['profile_32',['Experimental Target Profile',['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCTarget',1,'']]],
  ['profiles_33',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['program_20memory_20data_34',['Program-Memory Data',['../group__Foundation__Utils.html#FoundationUtilsFlash',1,'']]],
  ['proves_35',['What It Proves',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCoverage',1,'']]],
  ['psoc_20creator_20usage_36',['PSoC Creator Usage',['../group__Foundation.html#FoundationTop_PSoCUsage',1,'']]],
  ['public_20api_37',['Public API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['public_20api_20policy_38',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['public_20headers_39',['Public Headers',['../group__Foundation__Containers.html#FoundationContainersHeaders',1,'Public Headers'],['../group__Foundation__Functional.html#FoundationFunctionalHeaders',1,'Public Headers'],['../group__Foundation__Time.html#FoundationTimeHeaders',1,'Public Headers'],['../group__Foundation__Scheduling.html#FoundationSchedulingHeaders',1,'Public Headers'],['../group__Foundation__Utils.html#FoundationUtilsHeaders',1,'Public Headers']]],
  ['public_20surface_20inventory_40',['Public Surface Inventory',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditInventory',1,'']]],
  ['public_20types_41',['Public Types',['../group__Foundation__Time.html#FoundationTimeTypes',1,'Public Types'],['../group__Foundation__Scheduling.html#FoundationSchedulingTypes',1,'Public Types']]],
  ['publication_42',['Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'Triggers and Publication'],['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowVerify',1,'Verification Before Publication']]],
  ['publication_43',['[1.0.0] - Superseded before publication',['../md_CHANGELOG.html#autotoc_md38',1,'']]],
  ['published_20v1_202_200_20downstream_20consumer_20—_202026_2009_2027_44',['Published v1.2.0 downstream consumer — 2026-09-27',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceReleasedConsumer',1,'']]]
];
