var searchData=
[
  ['recommended_20flow_0',['Recommended Flow',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledRecommendedFlow',1,'']]],
  ['recommended_20freeze_20decisions_1',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['recommended_20usage_2',['Recommended Usage',['../group__Foundation.html#FoundationTop_RecommendedUsage',1,'']]],
  ['record_3',['Result Record',['../group__Foundation__Workflows__Validation.html#FoundationValidationReport',1,'']]],
  ['recorded_20evidence_4',['Recorded Evidence',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidence',1,'']]],
  ['registered_20native_20suite_5',['Registered Native Suite',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestSuite',1,'']]],
  ['related_20components_6',['Related Components',['../group__Foundation__Callback.html#FoundationCallbackRelated',1,'']]],
  ['related_20modules_7',['Related Modules',['../group__Foundation__Matrix.html#FoundationMatrixRelated',1,'']]],
  ['related_20pages_8',['Related Pages',['../group__Foundation.html#Foundation_RelatedPages',1,'']]],
  ['related_20topics_9',['Related Topics',['../group__Foundation.html#FoundationTop_RelatedTopics',1,'']]],
  ['release_20and_20license_20status_10',['Release and License Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'']]],
  ['release_20candidate_20export_11',['Release-Candidate Export',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowExport',1,'']]],
  ['release_20contract_12',['M1 - Release Contract',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M1',1,'']]],
  ['release_20evidence_13',['Release Evidence',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationExit',1,'']]],
  ['release_20gates_14',['Release Gates',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Gates',1,'']]],
  ['release_20procedure_15',['Release Procedure',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesReleaseProcedure',1,'']]],
  ['release_20rule_16',['Release Rule',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixReleaseRule',1,'']]],
  ['release_20sequence_17',['Normal Release Sequence',['../group__Foundation__Workflows.html#FoundationWorkflowsSequence',1,'']]],
  ['releases_18',['M6 - Sustained 1.x Releases',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M6',1,'']]],
  ['repository_20facts_20collected_19',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['repository_20layout_20',['Repository Layout',['../index.html#MainPage_RepositoryLayout',1,'']]],
  ['representations_21',['Tick Representations',['../group__Foundation__Time.html#FoundationTimeRepresentations',1,'']]],
  ['required_20matrix_22',['Required Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMatrix',1,'']]],
  ['requirements_23',['Requirements',['../index.html#MainPage_Requirements',1,'']]],
  ['responsibilities_24',['Responsibilities',['../group__Foundation__Workflows.html#FoundationWorkflowsResponsibilities',1,'']]],
  ['responsibility_25',['Header Responsibility',['../group__Foundation.html#FoundationTop_HeaderResponsibility',1,'']]],
  ['result_26',['Inspecting the Result',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureInspect',1,'']]],
  ['result_20record_27',['Result Record',['../group__Foundation__Workflows__Validation.html#FoundationValidationReport',1,'']]],
  ['return_20values_28',['Return Values',['../group__Foundation__Callback.html#FoundationCallbackReturnValues',1,'']]],
  ['reusing_20an_20existing_20package_29',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['roadmap_30',['Dependency Roadmap',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Roadmap',1,'']]],
  ['rule_31',['Rule',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportCompatibility',1,'Compatibility Rule'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildRule',1,'General Rule'],['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixReleaseRule',1,'Release Rule'],['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Rule',1,'STM32 Rule']]],
  ['rules_32',['Rules',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetRules',1,'Extension Rules'],['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Rules',1,'Update Rules']]],
  ['runnable_20example_33',['Runnable Example',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsExample',1,'Runnable Example'],['../group__Foundation__Containers.html#FoundationContainersExample',1,'Runnable Example'],['../group__Foundation__Functional.html#FoundationFunctionalExample',1,'Runnable Example'],['../group__Foundation__Scheduling.html#FoundationSchedulingExample',1,'Runnable Example'],['../group__Foundation__Utils.html#FoundationUtilsExample',1,'Runnable Example']]],
  ['runnable_20examples_34',['Runnable Examples',['../group__Foundation__Time.html#FoundationTimeExamples',1,'']]],
  ['runtime_20and_20api_20boundaries_35',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]]
];
