var searchData=
[
  ['sanitizers_0',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['scheduling_1',['Scheduling',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageScheduling',1,'']]],
  ['scheduling_20module_2',['Scheduling Module',['../group__Foundation.html#Foundation_SchedulingModule',1,'']]],
  ['scope_3',['Scope',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Scope',1,'Library Scope'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'Method and Scope'],['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPlatforms',1,'Platform Scope'],['../group__Foundation__Workflows__Clean.html#FoundationWorkflowCleanScope',1,'Scope'],['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'Test-Suite Scope']]],
  ['sections_4',['Sections',['../group__Foundation__BuildGuide.html#FoundationBuildGuideSections',1,'']]],
  ['selective_20include_5',['Selective Include',['../group__Foundation.html#FoundationTop_SelectiveInclude',1,'']]],
  ['sequence_6',['Sequence',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRCommands',1,'Complete Local Sequence'],['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationSequence',1,'Job Sequence'],['../group__Foundation__Workflows.html#FoundationWorkflowsSequence',1,'Normal Release Sequence']]],
  ['set_20matrix_7',['Feature-Set Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'']]],
  ['settings_20header_8',['Build Settings Header',['../group__Foundation.html#FoundationTop_BuildSettingsHeader',1,'']]],
  ['severity_9',['Severity',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditSeverity',1,'']]],
  ['signature_20model_10',['Signature Model',['../group__Foundation__Callback.html#FoundationCallbackSignatures',1,'']]],
  ['source_20mode_11',['Source Mode',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoSource',1,'Source Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildSourceMode',1,'Source Mode']]],
  ['source_20mode_20integrations_12',['Source-Mode Integrations',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixSourceMode',1,'']]],
  ['started_13',['Getting Started',['../index.html#MainPage_GettingStarted',1,'']]],
  ['state_14',['Cached State',['../group__Foundation__Workflows.html#FoundationWorkflowsState',1,'']]],
  ['state_20and_20lifetime_15',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['status_16',['Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'Release and License Status'],['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditStatus',1,'Status'],['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageStatus',1,'Status'],['../index.html#MainPage_Platforms',1,'Target Platforms and Support Status'],['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsTests',1,'Test Status']]],
  ['status_20header_17',['Status Header',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1Status',1,'']]],
  ['steps_18',['Next Steps',['../index.html#MainPage_NextSteps',1,'']]],
  ['still_20open_19',['Quality Gates Still Open',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsQuality',1,'']]],
  ['stm32_20matrix_20',['STM32 Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationSTM32',1,'']]],
  ['stm32_20rule_21',['STM32 Rule',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Rule',1,'']]],
  ['storage_22',['External Storage',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicExternalStorage',1,'']]],
  ['storage_20and_20lifetime_20contract_23',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['strategies_24',['Include Strategies',['../group__Foundation.html#FoundationTop_IncludeStrategies',1,'']]],
  ['structure_25',['Group Structure',['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsStructure',1,'']]],
  ['style_26',['Coding Style',['../group__Foundation.html#Foundation_Style',1,'']]],
  ['suite_27',['Registered Native Suite',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestSuite',1,'']]],
  ['suite_20scope_28',['Test-Suite Scope',['../group__Foundation__Workflows__Validation.html#FoundationValidationCurrentLimits',1,'']]],
  ['superseded_20before_20publication_29',['[1.0.0] - Superseded before publication',['../md_CHANGELOG.html#autotoc_md18',1,'']]],
  ['support_20levels_30',['Support Levels',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixLevels',1,'']]],
  ['support_20status_31',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['supported_20families_32',['Supported Families',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFamilies',1,'']]],
  ['supported_20target_33',['Supported Target',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRTarget',1,'Initial Supported Target'],['../group__Foundation__BuildGuide__PSoC.html#FoundationBuildPSoCTarget',1,'Initial Supported Target']]],
  ['supported_20v1_20surface_34',['Supported v1 Surface',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsSurface',1,'']]],
  ['supported_20windows_20toolchains_35',['Supported Windows Toolchains',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsToolchains',1,'']]],
  ['surface_36',['Supported v1 Surface',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsSurface',1,'']]],
  ['surface_20inventory_37',['Public Surface Inventory',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditInventory',1,'']]],
  ['sustained_201_20x_20releases_38',['M6 - Sustained 1.x Releases',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M6',1,'']]],
  ['system_39',['Build System',['../group__Foundation.html#Foundation_BuildSystem',1,'']]]
];
