var searchData=
[
  ['facts_20collected_0',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['failure_20contract_1',['Failure Contract',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicFailure',1,'']]],
  ['failure_20evidence_2',['Failure Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationFailureEvidence',1,'']]],
  ['failures_3',['Common Failures',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildFailures',1,'']]],
  ['families_4',['Supported Families',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFamilies',1,'']]],
  ['feature_20dependencies_5',['Feature Dependencies',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureDependencies',1,'']]],
  ['feature_20matrix_6',['Feature Matrix',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureMatrix',1,'']]],
  ['feature_20set_20matrix_7',['Feature-Set Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'']]],
  ['feature_20variants_8',['Feature Variants',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportFeatures',1,'']]],
  ['features_9',['Features',['../group__Foundation__Matrix__Fixed.html#FoundationFixedFeatures',1,'']]],
  ['files_10',['Files',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFiles',1,'']]],
  ['findings_11',['Findings',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditFindings',1,'']]],
  ['firmware_20consumer_20—_202026_2009_2028_12',['STM32G0B1CBT6 firmware consumer — 2026-09-28',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceSTM32G0B1',1,'']]],
  ['firmware_20consumer_20on_20an_20arduino_20uno_20—_202026_2009_2026_13',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['fixed_14',['Fixed',['../md_CHANGELOG.html#autotoc_md11',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md13',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md15',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md17',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md19',1,'Fixed'],['../md_CHANGELOG.html#autotoc_md28',1,'Fixed']]],
  ['fixed_20matrices_15',['Fixed Matrices',['../group__Foundation__Matrix.html#FoundationMatrixFixed',1,'Fixed Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsFixed',1,'Fixed Matrices']]],
  ['flow_16',['Flow',['../group__Foundation__Scheduling.html#FoundationSchedulingFlow',1,'Execution Flow'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledRecommendedFlow',1,'Recommended Flow']]],
  ['for_20counsel_17',['Questions for Counsel',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCounsel',1,'']]],
  ['for_20development_18',['Building Examples for Development',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildExamples',1,'']]],
  ['for_20each_20preset_19',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['foundation_20',['Foundation',['../md_README.html',1,'']]],
  ['foundation_20documentation_21',['Foundation Documentation',['../index.html',1,'']]],
  ['foundation_20h_22',['Foundation.h',['../group__Foundation.html#FoundationTop_FoundationHeader',1,'']]],
  ['foundation_20options_23',['Foundation Options',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureOptions',1,'']]],
  ['foundation_5fbuildsettings_20h_24',['Foundation_BuildSettings.h',['../group__Foundation.html#FoundationTop_FoundationBuildSettingsHeader',1,'']]],
  ['foundation_5fcontainers_20h_25',['Foundation_Containers.h',['../group__Foundation.html#FoundationTop_ContainersHeader',1,'']]],
  ['foundation_5ffunctional_20h_26',['Foundation_Functional.h',['../group__Foundation.html#FoundationTop_FunctionalHeader',1,'']]],
  ['foundation_5fmath_20h_27',['Foundation_Math.h',['../group__Foundation.html#FoundationTop_MathHeader',1,'']]],
  ['foundation_5fscheduling_20h_28',['Foundation_Scheduling.h',['../group__Foundation.html#FoundationTop_SchedulingHeader',1,'']]],
  ['foundation_5ftime_20h_29',['Foundation_Time.h',['../group__Foundation.html#FoundationTop_TimeHeader',1,'']]],
  ['foundation_5futils_20h_30',['Foundation_Utils.h',['../group__Foundation.html#FoundationTop_UtilsHeader',1,'']]],
  ['free_20functions_31',['Free Functions',['../group__Foundation__Callback.html#FoundationCallbackFreeFunctions',1,'']]],
  ['freeze_20decisions_32',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['freeze_20exit_20criteria_33',['Freeze Exit Criteria',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditExit',1,'']]],
  ['fresh_34',['When to Use Fresh',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureFresh',1,'']]],
  ['fresh_20versus_20incremental_35',['Fresh Versus Incremental',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowFresh',1,'']]],
  ['full_20build_36',['Full Build',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledFullBuild',1,'']]],
  ['full_20include_37',['Full Include',['../group__Foundation.html#FoundationTop_FullInclude',1,'']]],
  ['full_20precompiled_20mode_38',['Full Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'']]],
  ['functional_39',['Functional',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageFunctional',1,'']]],
  ['functional_20module_40',['Functional Module',['../group__Foundation.html#Foundation_FunctionalModule',1,'']]],
  ['functions_41',['Functions',['../group__Foundation__Callback.html#FoundationCallbackFreeFunctions',1,'Free Functions'],['../group__Foundation__Callback.html#FoundationCallbackMemberFunctions',1,'Member Functions']]]
];
