var searchData=
[
  ['facts_20collected_0',['Repository Facts Collected',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewFacts',1,'']]],
  ['failure_20contract_1',['Failure Contract',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicFailure',1,'']]],
  ['failures_2',['Common Failures',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildFailures',1,'']]],
  ['families_3',['Families',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFamilies',1,'Supported Families'],['../group__Foundation__TypeTraits.html#FoundationTypeTraitsFamilies',1,'Trait Families']]],
  ['feature_20dependencies_4',['Feature Dependencies',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureDependencies',1,'']]],
  ['feature_20matrix_5',['Feature Matrix',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureMatrix',1,'']]],
  ['feature_20set_20matrix_6',['Feature-Set Matrix',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'']]],
  ['feature_20variants_7',['Feature Variants',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportFeatures',1,'']]],
  ['features_8',['Features',['../group__Foundation__Matrix__Fixed.html#FoundationFixedFeatures',1,'']]],
  ['files_9',['Files',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetFiles',1,'']]],
  ['findings_10',['Findings',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditFindings',1,'']]],
  ['fixed_20matrices_11',['Fixed Matrices',['../group__Foundation__Matrix.html#FoundationMatrixFixed',1,'Fixed Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsFixed',1,'Fixed Matrices']]],
  ['flow_12',['Flow',['../group__Foundation__Scheduling.html#FoundationSchedulingFlow',1,'Execution Flow'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledRecommendedFlow',1,'Recommended Flow']]],
  ['for_20counsel_13',['Questions for Counsel',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCounsel',1,'']]],
  ['for_20development_14',['Building Examples for Development',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildExamples',1,'']]],
  ['for_20each_20preset_15',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['foundation_16',['Foundation',['../md_README.html',1,'']]],
  ['foundation_20documentation_17',['Foundation Documentation',['../index.html',1,'']]],
  ['foundation_20h_18',['Foundation.h',['../group__Foundation.html#FoundationTop_FoundationHeader',1,'']]],
  ['foundation_20options_19',['Foundation Options',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureOptions',1,'']]],
  ['foundation_5fbuildsettings_20h_20',['Foundation_BuildSettings.h',['../group__Foundation.html#FoundationTop_FoundationBuildSettingsHeader',1,'']]],
  ['foundation_5fcontainers_20h_21',['Foundation_Containers.h',['../group__Foundation.html#FoundationTop_ContainersHeader',1,'']]],
  ['foundation_5ffunctional_20h_22',['Foundation_Functional.h',['../group__Foundation.html#FoundationTop_FunctionalHeader',1,'']]],
  ['foundation_5fmath_20h_23',['Foundation_Math.h',['../group__Foundation.html#FoundationTop_MathHeader',1,'']]],
  ['foundation_5fscheduling_20h_24',['Foundation_Scheduling.h',['../group__Foundation.html#FoundationTop_SchedulingHeader',1,'']]],
  ['foundation_5ftime_20h_25',['Foundation_Time.h',['../group__Foundation.html#FoundationTop_TimeHeader',1,'']]],
  ['foundation_5ftypetraits_20h_26',['Foundation_TypeTraits.h',['../group__Foundation.html#FoundationTop_TypeTraitsHeader',1,'']]],
  ['foundation_5futils_20h_27',['Foundation_Utils.h',['../group__Foundation.html#FoundationTop_UtilsHeader',1,'']]],
  ['free_20functions_28',['Free Functions',['../group__Foundation__Callback.html#FoundationCallbackFreeFunctions',1,'']]],
  ['freeze_20decisions_29',['Recommended Freeze Decisions',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditRecommendations',1,'']]],
  ['freeze_20exit_20criteria_30',['Freeze Exit Criteria',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditExit',1,'']]],
  ['fresh_31',['When to Use Fresh',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureFresh',1,'']]],
  ['fresh_20versus_20incremental_32',['Fresh Versus Incremental',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowFresh',1,'']]],
  ['full_20build_33',['Full Build',['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledFullBuild',1,'']]],
  ['full_20include_34',['Full Include',['../group__Foundation.html#FoundationTop_FullInclude',1,'']]],
  ['full_20precompiled_20mode_35',['Full Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'']]],
  ['functional_36',['Functional',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageFunctional',1,'']]],
  ['functional_20module_37',['Functional Module',['../group__Foundation.html#Foundation_FunctionalModule',1,'']]],
  ['functions_38',['Functions',['../group__Foundation__Callback.html#FoundationCallbackFreeFunctions',1,'Free Functions'],['../group__Foundation__Callback.html#FoundationCallbackMemberFunctions',1,'Member Functions']]]
];
