var searchData=
[
  ['m1_20release_20contract_0',['M1 - Release Contract',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M1',1,'']]],
  ['m2_20continuous_20integration_1',['M2 - Continuous Integration',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M2',1,'']]],
  ['m3_20test_20depth_20and_20code_20quality_2',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['m4_20package_20and_20workflow_20hardening_3',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['m5_20platform_20and_20hardware_20validation_4',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['m6_20sustained_201_20x_20releases_5',['M6 - Sustained 1.x Releases',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M6',1,'']]],
  ['macos_20arm64_20—_202026_2009_2025_6',['macOS Arm64 — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64',1,'']]],
  ['macos_20commands_7',['macOS Commands',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMacOS',1,'']]],
  ['macros_8',['Macros',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoMacros',1,'']]],
  ['main_20header_9',['Main Header',['../group__Foundation.html#FoundationTop_MainHeader',1,'']]],
  ['manual_20install_10',['Manual Install',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowInstall',1,'']]],
  ['math_11',['Math',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageMath',1,'']]],
  ['math_20module_12',['Math Module',['../group__Foundation.html#Foundation_MathModule',1,'']]],
  ['matrices_13',['Matrices',['../group__Foundation__Matrix.html#FoundationMatrixDynamic',1,'Dynamic Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsDynamic',1,'Dynamic Matrices'],['../group__Foundation__Matrix.html#FoundationMatrixFixed',1,'Fixed Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsFixed',1,'Fixed Matrices'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsMixed',1,'Mixed Matrices']]],
  ['matrix_14',['Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationAVR',1,'AVR Matrix'],['../group__Foundation__Workflows__Precompiled.html#FoundationPrecompiledCompatibilityMatrix',1,'Compatibility Matrix'],['../group__Foundation__Workflows__Validation.html#FoundationValidationDesktop',1,'Desktop Matrix'],['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationEmbedded',1,'Embedded Matrix'],['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigureMatrix',1,'Feature Matrix'],['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationFeatures',1,'Feature-Set Matrix'],['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationMatrix',1,'Native Matrix'],['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesMatrix',1,'Package Matrix'],['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationMatrix',1,'Required Matrix'],['../group__Foundation__Workflows__Validation.html#FoundationValidationSTM32',1,'STM32 Matrix']]],
  ['matrix_20types_15',['Matrix Types',['../group__Foundation__Matrix.html#FoundationMatrixTypes',1,'']]],
  ['member_20functions_16',['Member Functions',['../group__Foundation__Callback.html#FoundationCallbackMemberFunctions',1,'']]],
  ['memory_17',['Dynamic Memory',['../group__Foundation__BuildGuide__AVR.html#FoundationBuildAVRMemory',1,'']]],
  ['memory_20layout_18',['Memory Layout',['../group__Foundation__Matrix__Fixed.html#FoundationFixedLayout',1,'']]],
  ['metal_20local_20preflight_20—_202026_2009_2025_19',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['method_20and_20scope_20',['Method and Scope',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'']]],
  ['mixed_20matrices_21',['Mixed Matrices',['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsMixed',1,'']]],
  ['mode_22',['Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'Custom Precompiled Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'Full Precompiled Mode'],['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoSource',1,'Source Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildSourceMode',1,'Source Mode']]],
  ['mode_20integrations_23',['Source-Mode Integrations',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixSourceMode',1,'']]],
  ['model_24',['Model',['../group__Foundation.html#Foundation_DependencyModel',1,'Dependency Model'],['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowModel',1,'Execution Model'],['../group__Foundation__Callback.html#FoundationCallbackSignatures',1,'Signature Model']]],
  ['modular_20time_20and_20validity_25',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['module_26',['Module',['../group__Foundation.html#Foundation_ContainersModule',1,'Containers Module'],['../group__Foundation.html#Foundation_FunctionalModule',1,'Functional Module'],['../group__Foundation.html#Foundation_MathModule',1,'Math Module'],['../group__Foundation.html#Foundation_SchedulingModule',1,'Scheduling Module'],['../group__Foundation.html#Foundation_TimeModule',1,'Time Module'],['../group__Foundation.html#Foundation_TypeTraitsModule',1,'Type Traits Module'],['../group__Foundation.html#Foundation_UtilsModule',1,'Utils Module']]],
  ['module_20architecture_27',['Module Architecture',['../group__Foundation.html#Foundation_ModuleArchitecture',1,'']]],
  ['module_20availability_28',['Module Availability',['../group__Foundation.html#FoundationTop_ModuleAvailability',1,'']]],
  ['module_20dependencies_29',['Module Dependencies',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditDependencies',1,'']]],
  ['module_20headers_30',['Module Headers',['../group__Foundation.html#FoundationTop_ModuleHeaders',1,'']]],
  ['modules_31',['Modules',['../group__Foundation.html#Foundation_Modules',1,'Modules'],['../md_README.html#autotoc_md1',1,'Modules'],['../index.html#MainPage_Modules',1,'Modules'],['../group__Foundation__Matrix.html#FoundationMatrixRelated',1,'Related Modules']]],
  ['msvc_32',['MSVC',['../group__Foundation__BuildGuide__Windows.html#FoundationBuildWindowsMSVC',1,'']]]
];
