var searchData=
[
  ['a_20download_0',['Consuming a Download',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesConsumption',1,'']]],
  ['a_20target_1',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['acceptance_2',['Acceptance',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureAcceptance',1,'INFRA-001 Acceptance'],['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32G0Hardware',1,'STM32G0B1 Hardware Acceptance']]],
  ['acceptance_20and_20evidence_3',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['acceptance_20criteria_4',['Acceptance Criteria',['../group__Foundation__Workflows__Validation.html#FoundationValidationAcceptance',1,'']]],
  ['access_5',['Element Access',['../group__Foundation__Matrix__Fixed.html#FoundationFixedElementAccess',1,'']]],
  ['adapter_20contract_6',['Workflow Adapter Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureWorkflowAdapter',1,'']]],
  ['added_7',['Added',['../md_CHANGELOG.html#autotoc_md23',1,'Added'],['../md_CHANGELOG.html#autotoc_md25',1,'Added'],['../md_CHANGELOG.html#autotoc_md29',1,'Added'],['../md_CHANGELOG.html#autotoc_md33',1,'Added'],['../md_CHANGELOG.html#autotoc_md36',1,'Added'],['../md_CHANGELOG.html#autotoc_md39',1,'Added']]],
  ['adding_20a_20target_8',['Adding a Target',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAddTarget',1,'']]],
  ['adding_20an_20example_9',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['aliasing_10',['Aliasing',['../group__Foundation__Matrix__Dynamic.html#FoundationMatrixDynamicAliasing',1,'']]],
  ['an_20arduino_20uno_20—_202026_2009_2026_11',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['an_20example_12',['Adding an Example',['../group__Foundation__Examples.html#FoundationExamplesAdd',1,'']]],
  ['an_20existing_20package_13',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['anatomy_14',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['and_20api_20boundaries_15',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['and_20code_20quality_16',['M3 - Test Depth and Code Quality',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M3',1,'']]],
  ['and_20cross_20tests_17',['Native and Cross Tests',['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestNativeVsCross',1,'']]],
  ['and_20decision_18',['Status and Decision',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureStatus',1,'']]],
  ['and_20defaults_19',['and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['and_20evidence_20',['Acceptance and Evidence',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationAcceptance',1,'']]],
  ['and_20examples_21',['Tests and Examples',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowTests',1,'']]],
  ['and_20exception_20contract_22',['Compile-Time and Exception Contract',['../group__Foundation__Time.html#FoundationTimeCompileTime',1,'']]],
  ['and_20export_23',['Build and Export',['../group__Foundation__BuildGuide__STM32.html#FoundationBuildSTM32Commands',1,'']]],
  ['and_20hardware_20validation_24',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['and_20include_20contract_25',['Build and Include Contract',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageBuild',1,'']]],
  ['and_20installation_26',['Build and Installation',['../index.html#MainPage_Build',1,'']]],
  ['and_20launcher_20—_202026_2009_2026_27',['macOS Arm64 examples and launcher — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64Examples',1,'']]],
  ['and_20license_20status_28',['Release and License Status',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsRelease',1,'']]],
  ['and_20lifetime_29',['Binding State and Lifetime',['../group__Foundation__Callback.html#FoundationCallbackState',1,'']]],
  ['and_20lifetime_20contract_30',['Storage and Lifetime Contract',['../group__Foundation__Containers.html#FoundationContainersOwnership',1,'']]],
  ['and_20non_20goals_31',['Goals and Non-goals',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureGoals',1,'']]],
  ['and_20overrides_32',['Explicit Configuration and Overrides',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowConfigure',1,'']]],
  ['and_20permissions_33',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['and_20pinning_34',['Distribution and Pinning',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureDistribution',1,'']]],
  ['and_20publication_35',['Triggers and Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'']]],
  ['and_20sanitizers_36',['Warnings and Sanitizers',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationQuality',1,'']]],
  ['and_20scope_37',['Method and Scope',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditMethod',1,'']]],
  ['and_20support_20status_38',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['and_20timing_20contract_39',['Ownership and Timing Contract',['../group__Foundation__Scheduling.html#FoundationSchedulingOwnership',1,'']]],
  ['and_20toolchain_20contract_40',['Preset and Toolchain Contract',['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructurePresetContract',1,'']]],
  ['and_20validity_41',['Modular Time and Validity',['../group__Foundation__Time.html#FoundationTimeModel',1,'']]],
  ['and_20workflow_20hardening_42',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['api_43',['API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['api_20boundaries_44',['Runtime and API Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsLanguage',1,'']]],
  ['api_20policy_45',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['applications_46',['Applications',['../group__Foundation__Matrix.html#FoundationMatrixApplications',1,'Applications'],['../group__Foundation__Matrix__Fixed.html#FoundationFixedApplications',1,'Applications'],['../group__Foundation__MatrixOperations.html#FoundationMatrixOperationsApplications',1,'Applications']]],
  ['architecture_47',['Architecture',['../group__Foundation.html#Foundation_ModuleArchitecture',1,'Module Architecture'],['../group__Foundation__Workflows__SharedInfrastructure.html#FoundationSharedInfrastructureArchitecture',1,'Target Architecture']]],
  ['arduino_48',['Arduino',['../md_README.html#autotoc_md7',1,'']]],
  ['arduino_20libraries_49',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['arduino_20uno_20—_202026_2009_2026_50',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['arduino_20usage_51',['Arduino Usage',['../group__Foundation.html#FoundationTop_ArduinoUsage',1,'']]],
  ['arguments_20and_20defaults_52',['Arguments and Defaults',['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestArguments',1,'Arguments and Defaults'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportArguments',1,'Arguments and Defaults']]],
  ['arithmetic_20operations_53',['Arithmetic Operations',['../group__Foundation__Matrix__Fixed.html#FoundationFixedArithmetic',1,'']]],
  ['arm_20bare_20metal_20local_20preflight_20—_202026_2009_2025_54',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['arm_20embedded_55',['GNU Arm Embedded',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowArmToolchain',1,'']]],
  ['arm_20profiles_56',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['arm64_20—_202026_2009_2025_57',['macOS Arm64 — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64',1,'']]],
  ['arm64_20examples_20and_20launcher_20—_202026_2009_2026_58',['macOS Arm64 examples and launcher — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceMacOSArm64Examples',1,'']]],
  ['as_20executables_59',['Export as Executables',['../group__Foundation__Examples.html#FoundationExamplesExport',1,'']]],
  ['atmega328p_20—_202026_2009_2025_60',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['automated_20native_20validation_61',['Automated Native Validation',['../group__Foundation__Examples.html#FoundationExamplesValidation',1,'']]],
  ['availability_62',['Module Availability',['../group__Foundation.html#FoundationTop_ModuleAvailability',1,'']]],
  ['available_20native_20examples_63',['Available Native Examples',['../group__Foundation__Examples.html#FoundationExamplesAvailable',1,'']]],
  ['avr_20atmega328p_20—_202026_2009_2025_64',['AVR ATmega328P — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVR',1,'']]],
  ['avr_20firmware_20consumer_20on_20an_20arduino_20uno_20—_202026_2009_2026_65',['AVR firmware consumer on an Arduino Uno — 2026-09-26',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceAVRBoard',1,'']]],
  ['avr_20gcc_66',['AVR-GCC',['../group__Foundation__Workflows__Toolchains.html#FoundationWorkflowAVRToolchain',1,'']]],
  ['avr_20matrix_67',['AVR Matrix',['../group__Foundation__Workflows__Validation.html#FoundationValidationAVR',1,'']]]
];
