var searchData=
[
  ['package_0',['Reusing an Existing Package',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerReuse',1,'']]],
  ['package_20and_20workflow_20hardening_1',['M4 - Package and Workflow Hardening',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M4',1,'']]],
  ['package_20boundaries_2',['Package Boundaries',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPackages',1,'']]],
  ['package_20checks_3',['Package Checks',['../group__Foundation__Workflows__Validation.html#FoundationValidationPackage',1,'']]],
  ['package_20consumer_4',['Installed Package Consumer',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPackageConsumer',1,'']]],
  ['package_20layout_5',['Package Layout',['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportLayout',1,'']]],
  ['package_20matrix_6',['Package Matrix',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesMatrix',1,'']]],
  ['packet_20checklist_7',['Evidence Packet Checklist',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewPacket',1,'']]],
  ['pages_8',['Related Pages',['../group__Foundation.html#Foundation_RelatedPages',1,'']]],
  ['patterns_9',['Usage Patterns',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsPatterns',1,'']]],
  ['permissions_10',['Triggers and Permissions',['../group__Foundation__Workflows__ContinuousIntegration.html#FoundationContinuousIntegrationTriggers',1,'']]],
  ['platform_20and_20hardware_20validation_11',['M5 - Platform and Hardware Validation',['../group__Foundation__Workflows__ReleaseV1.html#FoundationReleaseV1M5',1,'']]],
  ['platform_20scope_12',['Platform Scope',['../group__Foundation__BuildGuide__KnownLimitations.html#FoundationKnownLimitationsPlatforms',1,'']]],
  ['platforms_13',['Target Platforms',['../group__Foundation.html#Foundation_TargetPlatforms',1,'']]],
  ['platforms_20and_20support_20status_14',['Target Platforms and Support Status',['../index.html#MainPage_Platforms',1,'']]],
  ['policy_15',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['position_16',['Current Position',['../group__Foundation__Workflows__LegalReview.html#FoundationLegalReviewCurrent',1,'']]],
  ['powershell_17',['PowerShell',['../group__Foundation__Workflows__Configure.html#FoundationWorkflowConfigurePowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Build.html#FoundationWorkflowBuildPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Test.html#FoundationWorkflowTestPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Install.html#FoundationWorkflowInstallPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Export.html#FoundationWorkflowExportPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Documentation.html#FoundationWorkflowDocsPowerShell',1,'PowerShell'],['../group__Foundation__Workflows__Clean.html#FoundationWorkflowCleanPowerShell',1,'PowerShell']]],
  ['precompiled_20arduino_20libraries_18',['Precompiled Arduino Libraries',['../group__Foundation__BuildGuide__Arduino.html#FoundationBuildArduinoPrecompiled',1,'']]],
  ['precompiled_20mode_19',['Precompiled Mode',['../group__Foundation__BuildGuide__Overview.html#FoundationBuildCustomPrecompiledMode',1,'Custom Precompiled Mode'],['../group__Foundation__BuildGuide__Overview.html#FoundationBuildFullPrecompiledMode',1,'Full Precompiled Mode']]],
  ['preflight_20',['Common Preflight',['../group__Foundation__Workflows__Validation.html#FoundationValidationPreflight',1,'']]],
  ['preflight_20—_202026_2009_2025_21',['Arm bare-metal local preflight — 2026-09-25',['../group__Foundation__Workflows__Validation.html#FoundationValidationEvidenceArmLocal',1,'']]],
  ['prerequisites_22',['Prerequisites',['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowPrerequisites',1,'']]],
  ['presentation_20contract_23',['Presentation Contract',['../group__Foundation__Examples.html#FoundationExamplesPresentation',1,'']]],
  ['preset_24',['Checklist for Each Preset',['../group__Foundation__Workflows__DesktopValidation.html#FoundationDesktopValidationCommon',1,'']]],
  ['preset_20anatomy_25',['Preset Anatomy',['../group__Foundation__Workflows__Presets.html#FoundationWorkflowPresetAnatomy',1,'']]],
  ['presets_26',['Workflow-Only Presets',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixWorkflowPresets',1,'']]],
  ['prioritized_20test_20work_27',['Prioritized Test Work',['../group__Foundation__Workflows__PublicApiCoverage.html#FoundationPublicApiCoverageNext',1,'']]],
  ['procedure_28',['Release Procedure',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesReleaseProcedure',1,'']]],
  ['profiles_29',['Generic Arm Profiles',['../group__Foundation__BuildGuide__SupportMatrix.html#FoundationSupportMatrixProfiles',1,'']]],
  ['proves_30',['What It Proves',['../group__Foundation__Workflows__PackageConsumer.html#FoundationPackageConsumerCoverage',1,'']]],
  ['psoc_20creator_20usage_31',['PSoC Creator Usage',['../group__Foundation.html#FoundationTop_PSoCUsage',1,'']]],
  ['public_20api_32',['Public API',['../group__Foundation.html#Foundation_PublicApi',1,'Public API'],['../index.html#MainPage_PublicApi',1,'Public API']]],
  ['public_20api_20policy_33',['Public API Policy',['../group__Foundation.html#FoundationTop_PublicApiPolicy',1,'']]],
  ['public_20headers_34',['Public Headers',['../group__Foundation__TypeTraits.html#FoundationTypeTraitsHeaders',1,'Public Headers'],['../group__Foundation__Containers.html#FoundationContainersHeaders',1,'Public Headers'],['../group__Foundation__Functional.html#FoundationFunctionalHeaders',1,'Public Headers'],['../group__Foundation__Time.html#FoundationTimeHeaders',1,'Public Headers'],['../group__Foundation__Scheduling.html#FoundationSchedulingHeaders',1,'Public Headers'],['../group__Foundation__Utils.html#FoundationUtilsHeaders',1,'Public Headers']]],
  ['public_20surface_20inventory_35',['Public Surface Inventory',['../group__Foundation__Workflows__PublicApiAudit.html#FoundationPublicApiAuditInventory',1,'']]],
  ['public_20types_36',['Public Types',['../group__Foundation__Time.html#FoundationTimeTypes',1,'Public Types'],['../group__Foundation__Scheduling.html#FoundationSchedulingTypes',1,'Public Types']]],
  ['publication_37',['Publication',['../group__Foundation__Workflows__ReleasePackages.html#FoundationReleasePackagesTriggers',1,'Triggers and Publication'],['../group__Foundation__Workflows__Manual.html#FoundationManualWorkflowVerify',1,'Verification Before Publication']]],
  ['publication_38',['[1.0.0] - Superseded before publication',['../md_CHANGELOG.html#autotoc_md18',1,'']]]
];
