#!/bin/sh

FOUNDATION_SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
FOUNDATION_ROOT=$(CDPATH= cd -- "$FOUNDATION_SCRIPT_DIR/.." && pwd)
FOUNDATION_BUILD_ROOT="$FOUNDATION_ROOT/build"
FOUNDATION_DIST_ROOT="$FOUNDATION_ROOT/dist"
FOUNDATION_ROMODULAR_SCRIPTS="$FOUNDATION_ROOT/tools/RoModularBuild/scripts"

if [ ! -f "$FOUNDATION_ROMODULAR_SCRIPTS/common.sh" ]; then
    printf '%s\n' \
        "error: RoModularBuild is unavailable; initialize tools/RoModularBuild with git submodule update --init --recursive" \
        >&2
    exit 2
fi

ROMODULAR_PROJECT_ROOT=$FOUNDATION_ROOT
ROMODULAR_BUILD_ROOT=$FOUNDATION_BUILD_ROOT
ROMODULAR_DIST_ROOT=$FOUNDATION_DIST_ROOT
ROMODULAR_PROJECT_LABEL=Foundation
ROMODULAR_CONFIGURE_COMMAND=scripts/configure.sh
ROMODULAR_DEFAULT_CONFIGURATION=Debug
ROMODULAR_DOCUMENTATION_PRESET=documentation
ROMODULAR_DOCUMENTATION_CONFIGURATION=Release
ROMODULAR_INSTALL_CONFIGURATION=Release
ROMODULAR_TESTING_CACHE_ARGUMENT=-DFOUNDATION_TESTING=ON
ROMODULAR_EXAMPLES_CACHE_ARGUMENT=-DFOUNDATION_EXAMPLES=ON

export \
    ROMODULAR_PROJECT_ROOT \
    ROMODULAR_BUILD_ROOT \
    ROMODULAR_DIST_ROOT \
    ROMODULAR_PROJECT_LABEL \
    ROMODULAR_CONFIGURE_COMMAND \
    ROMODULAR_DEFAULT_CONFIGURATION \
    ROMODULAR_DOCUMENTATION_PRESET \
    ROMODULAR_DOCUMENTATION_CONFIGURATION \
    ROMODULAR_INSTALL_CONFIGURATION \
    ROMODULAR_TESTING_CACHE_ARGUMENT \
    ROMODULAR_EXAMPLES_CACHE_ARGUMENT
